import type { InteractiveAILab } from '../../types/curriculum';

export const AI_INTERACTIVE_LABS: Partial<Record<number, InteractiveAILab>> = {
  12: {
    title: 'Un encargo, dos maneras de pedirlo',
    description: 'Ejecuta el mismo texto con una instrucción ambigua y otra que define objetivo, formato y límites. El modelo corre en tu navegador.',
    defaultMode: 'prompt',
    allowedModes: ['prompt'],
    systemPrompt: 'Responde en español. Sigue únicamente la instrucción del usuario y no inventes datos que no aparezcan en el texto.',
    promptA: 'Explica este texto.',
    promptB: 'Explícalo para una persona que empieza: usa tres viñetas, define el término principal y termina con una pregunta de comprobación.',
    input: 'Una variable permite asociar un nombre a un valor para poder consultarlo o cambiarlo más adelante durante la ejecución de un programa.',
    observationPrompt: '¿Qué cambió entre las respuestas y qué parte concreta del prompt produjo esa diferencia?',
  },
  14: {
    title: 'Zero-shot frente a few-shot',
    description: 'Compara una regla escrita solo con palabras contra la misma regla acompañada por ejemplos. No busques cuál suena mejor: observa cuál mantiene el formato.',
    defaultMode: 'prompt',
    allowedModes: ['prompt'],
    systemPrompt: 'Clasifica mensajes de soporte. Devuelve solo una etiqueta: cuenta, pago o técnico.',
    promptA: 'Clasifica el mensaje.',
    promptB: 'Clasifica el mensaje. Ejemplos: “No puedo iniciar sesión” → cuenta; “Me cobraron dos veces” → pago; “La pantalla queda en blanco” → técnico. Devuelve solo la etiqueta.',
    input: 'Desde esta mañana la aplicación se cierra justo después de tocar el botón para abrir mi perfil.',
    observationPrompt: '¿Observas una diferencia de formato o consistencia? Señala la evidencia, no una impresión general.',
  },
  24: {
    title: 'Inferencia local: capacidad y límites',
    description: 'Prueba un modelo pequeño sin enviar el texto a un servidor. Cambia la precisión del encargo y observa calidad, latencia y límites.',
    defaultMode: 'prompt',
    allowedModes: ['prompt', 'summarize', 'write'],
    systemPrompt: 'Eres un asistente breve que responde en español y reconoce cuando falta información.',
    promptA: 'Dame ideas sobre esto.',
    promptB: 'Propón dos acciones realizables hoy. Para cada una indica objetivo, primer paso y una limitación. No añadas datos externos.',
    input: 'Una biblioteca comunitaria quiere ayudar a principiantes a aprender programación con equipos antiguos y conexión a internet inestable.',
    observationPrompt: '¿Qué diferencias observas en utilidad y obediencia? Incluye la latencia mostrada como parte de la evidencia.',
  },
  26: {
    title: 'Transformers.js + WebGPU en acción',
    description: 'Inspecciona el modelo, su tamaño, formatos y caché antes de descargarlo. Luego genera en streaming con el modelo local LFM2.5 de 350M parámetros y precisión q4.',
    defaultMode: 'prompt',
    allowedModes: ['prompt', 'summarize', 'write'],
    systemPrompt: 'Actúa como tutor de programación para principiantes. Explica en español con palabras sencillas y ejemplos pequeños.',
    promptA: 'Explica las funciones.',
    promptB: 'Explica qué problema resuelve una función, separa parámetro y retorno, y muestra una analogía cotidiana en menos de 100 palabras.',
    input: 'Una función recibe datos de entrada, ejecuta instrucciones que pueden reutilizarse y puede devolver un resultado al lugar desde donde fue llamada.',
    observationPrompt: '¿Qué cambió al precisar el prompt? Anota también qué observaste sobre descarga, caché, velocidad y ejecución WebGPU.',
  },
  27: {
    title: 'Una tarea, contratos distintos',
    description: 'Resume y reescribe con inferencia local. Después contrasta el contrato con las APIs de tareas que algunos navegadores ofrecen de forma integrada.',
    defaultMode: 'summarize',
    allowedModes: ['summarize', 'write', 'prompt'],
    systemPrompt: 'Conserva los hechos del texto. No agregues nombres, cifras ni conclusiones nuevas.',
    promptA: 'Resume el texto de forma breve y fiel.',
    promptB: 'Devuelve un resumen de tres puntos: problema, decisión y siguiente paso. Usa lenguaje claro para una persona no técnica.',
    input: 'El equipo detectó que las respuestas tardaban demasiado porque el modelo se descargaba en cada visita. Decidió mostrar el tamaño antes de la descarga, conservar los archivos en caché y medir por separado el tiempo de carga y el de generación. El siguiente paso es probar el flujo en equipos sin WebGPU.',
    observationPrompt: '¿Qué información cambió o se perdió entre formatos? Cita evidencia del texto original y de la salida.',
  },
};
