export interface RoadmapCoverageTopic {
  id: string;
  label: string;
  aliases: string[];
  area: string;
}

export const AI_ENGINEER_ROADMAP_TOPICS: RoadmapCoverageTopic[] = [
  { id: 'role', label: 'Qué hace un AI Engineer', aliases: ['AI Engineer', 'integra modelos'], area: 'introducción' },
  { id: 'roles', label: 'Roles y responsabilidades', aliases: ['responsabilidades', 'ML Engineer'], area: 'introducción' },
  { id: 'agi', label: 'AI frente a AGI', aliases: ['AGI', 'capacidad general'], area: 'introducción' },
  { id: 'tokens', label: 'Tokens y tokenización', aliases: ['Tokenización', 'tokens'], area: 'LLM' },
  { id: 'context-window', label: 'Ventana de contexto', aliases: ['Ventana de contexto'], area: 'LLM' },
  { id: 'inference', label: 'Inferencia', aliases: ['Inferencia'], area: 'LLM' },
  { id: 'sampling', label: 'Sampling, temperatura, top-k y top-p', aliases: ['top-k', 'top-p', 'temperatura'], area: 'LLM' },
  { id: 'penalties', label: 'Penalizaciones de repetición', aliases: ['Penalización', 'repetición'], area: 'LLM' },
  { id: 'training', label: 'Entrenamiento y fine-tuning', aliases: ['Entrenamiento', 'fine-tuning'], area: 'LLM' },
  { id: 'prompt-anatomy', label: 'Anatomía del prompt', aliases: ['Anatomía', 'prompt'], area: 'prompts' },
  { id: 'system-role', label: 'Sistema, rol y conducta', aliases: ['system', 'rol'], area: 'prompts' },
  { id: 'constraints', label: 'Contexto y restricciones', aliases: ['restricciones'], area: 'prompts' },
  { id: 'structured', label: 'Salida estructurada', aliases: ['JSON Schema', 'salida estructurada'], area: 'prompts' },
  { id: 'zero-few', label: 'Zero-shot y few-shot', aliases: ['Zero-shot', 'few-shot'], area: 'prompts' },
  { id: 'react-cot', label: 'ReAct y chain of thought', aliases: ['ReAct', 'cadena de pensamiento'], area: 'prompts' },
  { id: 'function-calling', label: 'Function calling', aliases: ['function calling', 'tools'], area: 'prompts' },
  { id: 'stream-cache', label: 'Streaming y caché', aliases: ['streaming', 'caché'], area: 'prompts' },
  { id: 'context-engineering', label: 'Context engineering', aliases: ['Context engineering'], area: 'contexto' },
  { id: 'context-sources', label: 'Fuentes y capas de contexto', aliases: ['capas de contexto', 'fuentes'], area: 'contexto' },
  { id: 'context-security', label: 'Seguridad de contexto', aliases: ['seguridad de contexto', 'no confiable'], area: 'contexto' },
  { id: 'dynamic-filters', label: 'RAG y filtros dinámicos', aliases: ['filtros', 'RAG'], area: 'contexto' },
  { id: 'memory', label: 'Memoria, estado e historial', aliases: ['memoria', 'historial'], area: 'contexto' },
  { id: 'compaction', label: 'Compactación y contexto largo', aliases: ['compactación', 'contexto largo'], area: 'contexto' },
  { id: 'isolation', label: 'Aislamiento y fallos de contexto', aliases: ['aislamiento', 'fallos de contexto'], area: 'contexto' },
  { id: 'model-types', label: 'Modelos preentrenados, abiertos y cerrados', aliases: ['preentrenado', 'pesos abiertos'], area: 'modelos' },
  { id: 'self-hosted', label: 'Modelos locales o self-hosted', aliases: ['modelo local', 'alojado'], area: 'modelos' },
  { id: 'hf', label: 'Hugging Face Hub, tareas y Transformers.js', aliases: ['Hugging Face', 'Transformers.js'], area: 'modelos' },
  { id: 'local-platforms', label: 'Ollama y LM Studio', aliases: ['Ollama', 'LM Studio'], area: 'modelos' },
  { id: 'router', label: 'OpenRouter y APIs compatibles', aliases: ['OpenRouter', 'compatible'], area: 'modelos' },
  { id: 'model-families', label: 'Familias de modelos y proveedores', aliases: ['Claude', 'Gemini', 'Llama', 'Mistral', 'DeepSeek', 'Qwen', 'Gemma'], area: 'modelos' },
  { id: 'embedding-use', label: 'Búsqueda, clasificación, recomendación y anomalías', aliases: ['búsqueda semántica', 'clasificación', 'recomendación', 'anomalía'], area: 'embeddings' },
  { id: 'embedding-models', label: 'Modelos locales y APIs de embeddings', aliases: ['Sentence Transformers', 'Jina', 'API de embeddings'], area: 'embeddings' },
  { id: 'vector-db', label: 'Bases vectoriales', aliases: ['Chroma', 'Pinecone', 'Weaviate', 'FAISS', 'LanceDB', 'Qdrant', 'Supabase', 'MongoDB Atlas'], area: 'vectores' },
  { id: 'vector-search', label: 'Indexación y búsqueda por similitud', aliases: ['indexar', 'similitud'], area: 'vectores' },
  { id: 'rag', label: 'RAG, casos de uso y fine-tuning', aliases: ['RAG', 'fine-tuning'], area: 'RAG' },
  { id: 'rag-pipeline', label: 'Chunking, embedding, retrieval y generación', aliases: ['chunk', 'recuperación', 'generación'], area: 'RAG' },
  { id: 'rag-frameworks', label: 'SDK directo, LangChain, LlamaIndex, Haystack y RAGFlow', aliases: ['SDK directo', 'LangChain', 'LlamaIndex', 'Haystack', 'RAGFlow'], area: 'RAG' },
  { id: 'agents', label: 'Casos de agente, ReAct, tools y multi-agent', aliases: ['agente', 'ReAct', 'multiagente'], area: 'agentes' },
  { id: 'agent-implementation', label: 'Implementación manual y SDKs de agentes', aliases: ['bucle manual', 'Agents SDK', 'ADK', 'Vertex AI Agent Builder'], area: 'agentes' },
  { id: 'mcp-core', label: 'Host, cliente, servidor, datos y transporte MCP', aliases: ['MCP host', 'MCP client', 'MCP server', 'transporte'], area: 'MCP' },
  { id: 'mcp-connect', label: 'Servidor MCP local y remoto', aliases: ['stdio', 'Streamable HTTP'], area: 'MCP' },
  { id: 'safety', label: 'Inyección, privacidad, sesgo y moderación', aliases: ['prompt injection', 'privacidad', 'sesgo', 'moderación'], area: 'seguridad' },
  { id: 'production-controls', label: 'Identidad, casos permitidos y límites', aliases: ['end-user id', 'usos permitidos', 'límites'], area: 'seguridad' },
  { id: 'eval-types', label: 'Evaluaciones deterministas, humanas y con modelos', aliases: ['determinista', 'evaluación humana', 'model grader'], area: 'evaluación' },
  { id: 'eval-tools', label: 'DeepEval y Ragas', aliases: ['DeepEval', 'Ragas'], area: 'evaluación' },
  { id: 'observability', label: 'Trazas, coste, latencia y producción', aliases: ['trazas', 'coste', 'latencia', 'producción'], area: 'observabilidad' },
  { id: 'observability-tools', label: 'LangSmith, Langfuse, Helicone y Arize', aliases: ['LangSmith', 'Langfuse', 'Helicone', 'Arize'], area: 'observabilidad' },
  { id: 'regression', label: 'Pruebas de regresión', aliases: ['regresión'], area: 'evaluación' },
  { id: 'multimodal', label: 'Imagen, video, audio, TTS y STT', aliases: ['imagen', 'video', 'TTS', 'transcripción'], area: 'multimodal' },
  { id: 'multimodal-apis', label: 'APIs multimodales', aliases: ['OpenAI Vision', 'DALL-E', 'Nano Banana', 'Whisper'], area: 'multimodal' },
  { id: 'coding-tools', label: 'Claude Code, Gemini, Codex, Cursor, Windsurf y Replit', aliases: ['Claude Code', 'Gemini', 'Codex', 'Cursor', 'Windsurf', 'Replit'], area: 'desarrollo' },
  { id: 'context-tools', label: 'Modus, DataHub, Atlan y PostHog', aliases: ['Modus', 'DataHub', 'Atlan', 'PostHog'], area: 'contexto' },
];
