import type { ReadingSource } from '../../types/curriculum';
import type { AISourceId } from './types';

export const AI_SOURCES: Record<AISourceId, ReadingSource> = {
  'roadmap-ai-engineer': { title: 'AI Engineer Roadmap', url: 'https://roadmap.sh/ai-engineer', publisher: 'roadmap.sh', purpose: 'Mapa general de capacidades y responsabilidades del rol.' },
  'pyodide-usage': { title: 'Using Pyodide', url: 'https://pyodide.org/en/stable/usage/index.html', publisher: 'Pyodide', purpose: 'Ejecución de Python y paquetes dentro del navegador.' },
  'pyodide-worker': { title: 'Using Pyodide in a Web Worker', url: 'https://pyodide.org/en/stable/usage/webworker.html', publisher: 'Pyodide', purpose: 'Aislamiento del runtime para no bloquear la interfaz.' },
  'hf-llm-course': { title: 'Hugging Face LLM Course', url: 'https://huggingface.co/learn/llm-course/', publisher: 'Hugging Face', purpose: 'Fundamentos de modelos, tokenización, entrenamiento e inferencia.' },
  'transformers-js': { title: 'Transformers.js', url: 'https://huggingface.co/docs/transformers.js/index', publisher: 'Hugging Face', purpose: 'Modelos de inferencia que corren directamente en el navegador.' },
  'hf-model-hub': { title: 'Hugging Face Hub documentation', url: 'https://huggingface.co/docs/hub/models-the-hub', publisher: 'Hugging Face', purpose: 'Model cards, tareas, artefactos y evaluación de modelos publicados.' },
  'openai-prompting': { title: 'Prompt engineering', url: 'https://platform.openai.com/docs/guides/prompt-engineering', publisher: 'OpenAI', purpose: 'Ejemplo de guía de proveedor para diseñar instrucciones.' },
  'openai-function-calling': { title: 'Function calling', url: 'https://platform.openai.com/docs/guides/function-calling', publisher: 'OpenAI', purpose: 'Contrato de herramientas y argumentos estructurados.' },
  'google-prompt-design': { title: 'Prompt design strategies', url: 'https://ai.google.dev/gemini-api/docs/prompting-strategies', publisher: 'Google AI for Developers', purpose: 'Estrategias de instrucciones, ejemplos y contexto.' },
  'google-structured-output': { title: 'Structured outputs', url: 'https://ai.google.dev/gemini-api/docs/structured-output', publisher: 'Google AI for Developers', purpose: 'Respuestas JSON restringidas por esquema.' },
  'google-function-calling': { title: 'Function calling', url: 'https://ai.google.dev/gemini-api/docs/function-calling', publisher: 'Google AI for Developers', purpose: 'Declaración y ejecución de herramientas.' },
  'anthropic-prompt-engineering': { title: 'Prompt engineering overview', url: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview', publisher: 'Anthropic', purpose: 'Proceso de diseño y prueba de instrucciones.' },
  'anthropic-tool-use': { title: 'Tool use', url: 'https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/overview', publisher: 'Anthropic', purpose: 'Esquemas, llamadas y resultados de herramientas.' },
  'anthropic-prompt-caching': { title: 'Prompt caching', url: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching', publisher: 'Anthropic', purpose: 'Reutilización de prefijos de contexto y sus límites.' },
  'sentence-transformers-semantic-search': { title: 'Semantic Search', url: 'https://www.sbert.net/examples/sentence_transformer/applications/semantic-search/README.html', publisher: 'Sentence Transformers', purpose: 'Embeddings, similitud y recuperación semántica.' },
  'qdrant-vector-search': { title: 'Search', url: 'https://qdrant.tech/documentation/concepts/search/', publisher: 'Qdrant', purpose: 'Consultas vectoriales, puntuaciones y parámetros de búsqueda.' },
  'qdrant-filtering': { title: 'Filtering', url: 'https://qdrant.tech/documentation/concepts/filtering/', publisher: 'Qdrant', purpose: 'Metadatos, condiciones y combinación con búsqueda vectorial.' },
  'rag-paper': { title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks', url: 'https://arxiv.org/abs/2005.11401', publisher: 'Lewis et al.', purpose: 'Artículo original que formaliza la combinación de recuperación y generación.' },
  'mcp-architecture': { title: 'Architecture overview', url: 'https://modelcontextprotocol.io/docs/learn/architecture', publisher: 'Model Context Protocol', purpose: 'Relación entre host, cliente y servidor MCP.' },
  'mcp-specification': { title: 'Model Context Protocol specification', url: 'https://modelcontextprotocol.io/specification/', publisher: 'Model Context Protocol', purpose: 'Contratos de recursos, prompts, tools y transportes.' },
  'owasp-genai-top10': { title: 'OWASP Top 10 for LLM Applications', url: 'https://genai.owasp.org/llm-top-10/', publisher: 'OWASP GenAI Security Project', purpose: 'Riesgos frecuentes y controles para aplicaciones con modelos.' },
  'owasp-prompt-injection': { title: 'Prompt Injection', url: 'https://genai.owasp.org/llmrisk/llm01-prompt-injection/', publisher: 'OWASP GenAI Security Project', purpose: 'Inyección directa e indirecta y medidas de reducción de riesgo.' },
  'ragas-metrics': { title: 'Ragas metrics', url: 'https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/', publisher: 'Ragas', purpose: 'Métricas específicas para recuperación y generación.' },
  'deepeval-evaluation': { title: 'LLM evaluation', url: 'https://deepeval.com/docs/getting-started', publisher: 'DeepEval', purpose: 'Casos, métricas y pruebas de regresión para sistemas de IA.' },
  'ollama-api': { title: 'Ollama API', url: 'https://docs.ollama.com/api/introduction', publisher: 'Ollama', purpose: 'Ejecución local mediante una API HTTP y modelos instalados en el equipo.' },
  'lmstudio-api': { title: 'LM Studio Developer Docs', url: 'https://lmstudio.ai/docs/developer', publisher: 'LM Studio', purpose: 'Servidor local, SDKs de JavaScript y Python y endpoints compatibles.' },
  'openrouter-api': { title: 'OpenRouter quickstart', url: 'https://openrouter.ai/docs/quickstart', publisher: 'OpenRouter', purpose: 'Enrutamiento de varios proveedores mediante un contrato de API común.' },
  'jina-embeddings': { title: 'Jina Embeddings', url: 'https://jina.ai/embeddings/', publisher: 'Jina AI', purpose: 'Familia de modelos y API de embeddings para texto y datos multimodales.' },
  'langchain-retrieval': { title: 'Retrieval', url: 'https://docs.langchain.com/oss/python/langchain/retrieval', publisher: 'LangChain', purpose: 'Bloques y arquitecturas para búsqueda semántica y RAG.' },
  'llamaindex-rag': { title: 'Building a RAG pipeline', url: 'https://docs.llamaindex.ai/en/stable/understanding/rag/', publisher: 'LlamaIndex', purpose: 'Carga, indexación, almacenamiento, consulta y evaluación de datos para RAG.' },
  'haystack-intro': { title: 'Introduction to Haystack', url: 'https://docs.haystack.deepset.ai/docs/intro', publisher: 'Haystack', purpose: 'Pipelines, document stores, agentes y componentes de recuperación.' },
  'ragflow-docs': { title: 'RAGFlow', url: 'https://ragflow.io/', publisher: 'RAGFlow', purpose: 'Motor integrado de ingesta, búsqueda híbrida, RAG y flujos de agentes.' },
  'openai-agents-sdk': { title: 'OpenAI Agents SDK for TypeScript', url: 'https://openai.github.io/openai-agents-js/', publisher: 'OpenAI', purpose: 'Agentes, tools, handoffs, guardrails, sesiones y trazas.' },
  'anthropic-agent-sdk': { title: 'Claude Agent SDK overview', url: 'https://platform.claude.com/docs/en/agent-sdk/overview', publisher: 'Anthropic', purpose: 'Construcción de agentes con el mismo bucle y herramientas usados por Claude Code.' },
  'google-adk': { title: 'Agent Development Kit', url: 'https://google.github.io/adk-docs/', publisher: 'Google', purpose: 'Desarrollo y evaluación de agentes mediante ADK.' },
  'vertex-agent-builder': { title: 'Vertex AI Agent Builder', url: 'https://docs.cloud.google.com/agent-builder', publisher: 'Google Cloud', purpose: 'Suite gestionada para crear, desplegar y gobernar agentes.' },
  'langsmith-observability': { title: 'LangSmith observability', url: 'https://docs.langchain.com/langsmith/observability', publisher: 'LangChain', purpose: 'Trazas, paneles y depuración de aplicaciones con modelos.' },
  'langfuse-docs': { title: 'Langfuse documentation', url: 'https://langfuse.com/docs', publisher: 'Langfuse', purpose: 'Trazas, prompts, evaluaciones y métricas de uso.' },
  'helicone-docs': { title: 'Helicone documentation', url: 'https://docs.helicone.ai/', publisher: 'Helicone', purpose: 'Gateway y observabilidad para llamadas a proveedores de modelos.' },
  'arize-phoenix': { title: 'Arize Phoenix documentation', url: 'https://arize.com/docs/phoenix', publisher: 'Arize', purpose: 'Trazas OpenTelemetry, evaluación y análisis de sistemas de IA.' },
  'openai-image-audio': { title: 'Images and vision', url: 'https://platform.openai.com/docs/guides/images-vision', publisher: 'OpenAI', purpose: 'Contratos de entrada visual, análisis, generación y edición de imágenes.' },
  'google-video-understanding': { title: 'Video understanding', url: 'https://ai.google.dev/gemini-api/docs/video-understanding', publisher: 'Google AI for Developers', purpose: 'Carga de video, marcas temporales y consultas sobre contenido audiovisual.' },
  'datahub-docs': { title: 'DataHub documentation', url: 'https://docs.datahub.com/docs/', publisher: 'DataHub', purpose: 'Catálogo, metadatos y descubrimiento de fuentes de datos.' },
  'atlan-docs': { title: 'Atlan developer portal', url: 'https://developer.atlan.com/', publisher: 'Atlan', purpose: 'APIs y SDKs para catálogo y contexto de datos.' },
  'posthog-llm-analytics': { title: 'LLM analytics', url: 'https://posthog.com/docs/llm-analytics', publisher: 'PostHog', purpose: 'Seguimiento de generaciones, costes, latencia y comportamiento de producto.' },
};

export function sourcesFor(ids: AISourceId[]): ReadingSource[] {
  return ids.map((id) => ({ ...AI_SOURCES[id] }));
}
