import type { ReadingItem } from '../../types/curriculum';
import { enrichOpenCellsSections } from './lessonStructure';

interface AdvancedUnit {
  number: number;
  title: string;
  summary: string;
  model: string;
  contract: string;
  failure: string;
  keyPoints: string[];
}

function unit(source: AdvancedUnit): ReadingItem {
  return {
    id: `open-cells-${String(source.number).padStart(2, '0')}-lectura`,
    type: 'reading',
    title: source.title,
    summary: source.summary,
    estimatedMinutes: 12,
    sections: enrichOpenCellsSections(source.number, source.title, source.summary, [
      { title: 'Modelo mental', content: source.model },
      {
        title: 'Contrato en un proyecto',
        content: source.contract,
        example: `Predice el resultado, cambia una sola entrada y comprueba el comportamiento público relacionado con “${source.title}”.`,
        exampleCaption: 'La comprobación observa el contrato, no una línea memorizada.',
      },
      { title: 'Errores frecuentes y diagnóstico', content: source.failure },
    ]),
    keyPoints: source.keyPoints,
    transferPrompt: `Aplica “${source.title}” a una aplicación de turnos: identifica el archivo propietario, el contrato observable y una prueba que evite valores fijos.`,
    frequentQuestions: [
      { question: '¿Qué debo decidir antes de editar?', answer: 'Primero identifica la frontera propietaria, la entrada que cambia y la evidencia observable que demostrará el resultado.' },
      { question: '¿Cómo evito una solución rígida?', answer: 'Comprueba al menos dos entradas distintas y conserva una única fuente de verdad para la decisión.' },
    ],
  };
}

export const OPEN_CELLS_ADVANCED_UNITS: ReadingItem[] = [
  unit({ number: 69, title: 'Ciclo de vida y actualizaciones seguras', summary: 'Conecta los callbacks de Lit y Cells con cambios observables sin duplicar trabajo ni conservar efectos abandonados.', model: 'Una instancia nace, se conecta, actualiza su render y puede desconectarse. Cada callback responde a un momento distinto: inicializar estado, reaccionar después del render o liberar suscripciones.', contract: 'academy-lifecycle-panel inicia una observación al conectarse, deriva su vista desde propiedades reactivas y la detiene al desconectarse. Una reconexión no debe duplicar listeners ni contadores.', failure: 'Suscribirse en cada render multiplica efectos. Si un contador aumenta dos veces después de reconectar, revisa dónde se crea y dónde se libera la suscripción.', keyPoints: ['Cada efecto tiene propietario y cleanup.', 'updated no sustituye propiedades derivadas.', 'Reconectar no duplica observadores.'] }),
  unit({ number: 70, title: 'Contexto: proveedores y consumidores', summary: 'Usa contexto para dependencias ambientales compartidas sin convertir cada dato en una propiedad global.', model: 'Un proveedor publica una capacidad para su subárbol y los consumidores la solicitan. El contexto es apropiado para idioma, tema o sesión ambiental; una entrada específica del componente sigue siendo propiedad.', contract: 'academy-context-panel consume una preferencia de densidad provista por la demo. Al cambiar el proveedor, dos consumidores se actualizan sin importar entre sí ni leer una variable global.', failure: 'Crear dos símbolos distintos con la misma descripción rompe el contrato. Si el consumidor usa el valor por defecto, compara la identidad del contexto y el lugar del proveedor.', keyPoints: ['Proveedor y consumidor comparten identidad.', 'El alcance pertenece al árbol.', 'Las entradas específicas siguen siendo propiedades.'] }),
  unit({ number: 71, title: 'Imágenes e iconos configurables', summary: 'Modela recursos visuales como entradas accesibles, reemplazables y comprobables.', model: 'Una imagen comunica contenido; un icono puede ser informativo o decorativo. El componente recibe URL, texto alternativo y tamaño como contrato, sin acoplarse a una ruta interna del consumidor.', contract: 'academy-media-tile permite cambiar src y alt desde la demo, reserva espacio antes de cargar y oculta el icono decorativo a tecnologías de asistencia.', failure: 'Una ruta relativa puede funcionar en la demo y fallar al empaquetar. Si aparece un espacio vacío, revisa la URL resuelta, el evento de error y el texto alternativo antes de tocar estilos.', keyPoints: ['Los recursos entran por API pública.', 'alt depende de la intención.', 'El layout reserva dimensiones.'] }),
  unit({ number: 72, title: 'Tema, decisiones y ambientes visuales', summary: 'Separa tokens de diseño, preferencia del consumidor y estilos internos del componente.', model: 'El tema ofrece decisiones compartidas mediante tokens. El componente consume esos tokens y conserva su estructura; una variante pública solo existe cuando expresa una decisión semántica del consumidor.', contract: 'academy-theme-preview cambia entre dos ambientes desde la demo. El mismo componente usa variables consumibles y mantiene contraste, foco y estados sin duplicar una hoja completa.', failure: 'Fijar colores dentro del template impide tematizar y puede perder contraste. Si una variante no cambia, inspecciona la cascada y el valor calculado del token.', keyPoints: ['Los tokens expresan decisiones compartidas.', 'La variante es semántica.', 'Contraste y foco forman parte del contrato.'] }),
  unit({ number: 73, title: 'Flujo completo de la CLI de componentes', summary: 'Recorre creación, desarrollo, documentación, pruebas y entrega como un único circuito reproducible.', model: 'La CLI coordina artefactos, pero el contrato vive en archivos comprensibles: fuente, estilos generados, demo, locales, pruebas, metadatos y paquete.', contract: 'academy-component-workflow parte de un scaffold, modifica una propiedad, regenera estilos, actualiza la demo, ejecuta pruebas y produce un paquete que otro workspace puede consumir.', failure: 'Una demo verde con estilos editados a mano no garantiza una entrega reproducible. Reconstruye desde la fuente y prueba el paquete en un consumidor limpio.', keyPoints: ['La fuente genera artefactos.', 'Demo y pruebas son consumidores.', 'La entrega se reproduce desde cero.'] }),
  unit({ number: 74, title: 'Diseño técnico, plantillas y componentes transversales', summary: 'Convierte una necesidad de aplicación en fronteras, dependencias y decisiones verificables antes de implementar.', model: 'El diseño técnico describe responsabilidades, datos, navegación, componentes transversales y criterios de aceptación. No es un dibujo decorativo: limita acoplamientos antes de que se conviertan en código.', contract: 'academy-architecture-map separa shell, páginas, servicios y componentes compartidos. Cada flecha declara quién inicia la comunicación y qué contrato puede observarse.', failure: 'Una caja llamada utilidades suele ocultar varias responsabilidades. Divide por propietario y duración, y elimina dependencias circulares antes de abrir el editor.', keyPoints: ['Cada frontera tiene propietario.', 'Las dependencias apuntan a contratos.', 'Los criterios son observables.'] }),
  unit({ number: 75, title: 'Interceptores de navegación', summary: 'Interrumpe o redirige una navegación mediante reglas explícitas, asíncronas y comprobables.', model: 'Un interceptor recibe intención y contexto, después permite, cancela o redirige. No renderiza páginas ni modifica el historial por su cuenta.', contract: 'academy-route-guard protege una ruta con cambios pendientes. La decisión devuelve un resultado tipado y el router aplica una única transición.', failure: 'Disparar navegación dentro del interceptor crea bucles. Si una ruta se repite, registra intención, decisión y transición como tres pasos separados.', keyPoints: ['El interceptor decide; el router aplica.', 'La salida es tipada.', 'Una intención produce una transición.'] }),
  unit({ number: 76, title: 'Rutas delegadas y deep links', summary: 'Permite que un dominio gestione rutas internas sin perder una URL compartible ni el control del shell.', model: 'El shell reconoce un prefijo y delega el resto a un módulo. La ruta completa sigue siendo la fuente de verdad, por lo que recargar o compartir una URL reproduce la misma pantalla.', contract: 'academy-delegated-shell entrega /catalogo/:id al módulo de catálogo, que resuelve su página y conserva parámetros al volver atrás.', failure: 'Guardar la subruta solo en memoria rompe recarga y enlaces directos. Comprueba el arranque pegando la URL en una pestaña limpia.', keyPoints: ['La URL conserva el estado navegable.', 'El shell delega por prefijo.', 'El módulo no reescribe todo el historial.'] }),
  unit({ number: 77, title: 'Límite de páginas renderizadas', summary: 'Controla cuántas páginas permanecen montadas y qué estado merece sobrevivir a la navegación.', model: 'Retener una página puede acelerar el regreso, pero también conserva DOM, listeners y memoria. La política debe ser explícita: reemplazar, mantener una cantidad limitada o fijar una página justificada.', contract: 'academy-page-cache conserva como máximo dos páginas recientes y llama cleanup al expulsar la más antigua. El estado durable vive fuera de la instancia.', failure: 'Ocultar páginas sin desmontarlas parece funcionar hasta acumular listeners. Mide instancias y suscripciones después de varias navegaciones.', keyPoints: ['Retención es una política.', 'Evicción ejecuta cleanup.', 'Estado durable no depende del DOM retenido.'] }),
  unit({ number: 78, title: 'Feature flags con estado explícito', summary: 'Introduce capacidades de manera gradual sin repartir condicionales opacos por toda la aplicación.', model: 'Un flag tiene nombre, valor, propietario, fecha de revisión y comportamiento por defecto. La resolución ocurre en una frontera y las páginas consumen una decisión ya interpretada.', contract: 'academy-feature-toggle resuelve una experiencia nueva o estable a partir de configuración validada. Las pruebas cubren flag activo, inactivo y ausente.', failure: 'Leer strings directamente en cada componente produce interpretaciones distintas. Si dos pantallas discrepan, localiza las lecturas y centraliza la resolución.', keyPoints: ['Un flag tiene ciclo de vida.', 'La resolución es central.', 'Ausencia tiene comportamiento definido.'] }),
  unit({ number: 79, title: 'Service worker y políticas de caché', summary: 'Distingue instalación, activación, estrategias de caché y actualización visible para evitar una app eternamente vieja.', model: 'El service worker vive separado de la página. Intercepta peticiones según políticas concretas; no todas las respuestas merecen caché ni la misma caducidad.', contract: 'academy-offline-shell usa precache para el shell versionado y red para datos cambiantes. Una nueva versión informa al usuario antes de reemplazar recursos activos.', failure: 'Cachear todo oculta errores y sirve datos obsoletos. Inspecciona nombre de caché, estrategia por recurso y camino de actualización.', keyPoints: ['Cada recurso tiene estrategia.', 'La versión invalida el shell.', 'La actualización es visible.'] }),
  unit({ number: 80, title: 'Observabilidad y trazas', summary: 'Relaciona una acción del usuario con navegación, datos y render mediante señales útiles y sin filtrar contenido sensible.', model: 'Una traza conecta pasos con un identificador común; un log describe un evento; una métrica agrega comportamiento. Cada señal responde una pregunta operativa distinta.', contract: 'academy-trace-console propaga correlationId desde una selección hasta el resultado de datos y registra duración y estado sin copiar el contenido completo.', failure: 'Logs abundantes sin contexto no explican causalidad. Si no puedes reconstruir el recorrido, comprueba identificador, nombre estable y límites de privacidad.', keyPoints: ['Las trazas conectan causas.', 'Las métricas agregan.', 'No se registran secretos ni contenido innecesario.'] }),
  unit({ number: 81, title: 'Analítica con contratos de eventos', summary: 'Mide decisiones de producto mediante eventos versionados, mínimos y separados de la lógica visual.', model: 'Un evento analítico describe una acción o resultado mediante nombre estable y propiedades acordadas. La interfaz publica intención y un adaptador traduce al proveedor de medición.', contract: 'academy-analytics-contract valida nombre, versión y campos permitidos antes de enviar. La prueba usa un colector local y no depende de red.', failure: 'Enviar objetos completos mezcla datos privados y cambia el esquema sin control. Compara el contrato documentado con las propiedades emitidas.', keyPoints: ['El esquema está versionado.', 'La medición usa un adaptador.', 'Solo viajan datos necesarios.'] }),
  unit({ number: 82, title: 'Presupuestos de rendimiento', summary: 'Convierte rapidez y tamaño en límites medibles que guían decisiones antes de degradar la experiencia.', model: 'Un presupuesto fija máximos para carga, interacción, memoria o tamaño. No sustituye medir: hace visible cuándo una mejora local perjudica el conjunto.', contract: 'academy-performance-budget compara el artefacto y una navegación con umbrales declarados. El resultado explica cuál límite falló y por cuánto.', failure: 'Optimizar sin una línea base mueve trabajo de un lugar a otro. Repite la misma interacción y separa primera carga de navegación posterior.', keyPoints: ['El presupuesto es medible.', 'La línea base es reproducible.', 'Carga inicial y uso posterior se distinguen.'] }),
  unit({ number: 83, title: 'CI/CD y puertas de entrega', summary: 'Organiza comprobaciones automáticas para que una entrega avance solo con evidencia reproducible.', model: 'Integración valida cambios pequeños; entrega construye artefactos; despliegue promueve una versión. Cada puerta debe tener entrada, comando, evidencia y condición de fallo.', contract: 'academy-release-pipeline ejecuta formato, pruebas, build, inspección del paquete y prueba de consumo antes de marcar una versión lista.', failure: 'Un pipeline verde que reutiliza artefactos viejos da confianza falsa. Limpia el entorno y conserva evidencia del commit y del paquete exactos.', keyPoints: ['Cada puerta responde una pregunta.', 'El artefacto es inmutable.', 'La validación parte de un entorno limpio.'] }),
  unit({ number: 84, title: 'Estrategia de migración y compatibilidad', summary: 'Evoluciona contratos de componentes y aplicaciones sin obligar a todos los consumidores a cambiar al mismo tiempo.', model: 'Una migración define estado actual, destino, compatibilidad temporal, medición y retirada. El adaptador vive en una frontera y tiene fecha de eliminación.', contract: 'academy-migration-adapter acepta durante una versión una propiedad antigua y una nueva, normaliza ambas y emite un aviso verificable cuando se usa la anterior.', failure: 'Mantener compatibilidad sin fecha acumula dos productos. Mide usos restantes, documenta la retirada y prueba consumidores antiguos y nuevos.', keyPoints: ['La compatibilidad es temporal.', 'El adaptador normaliza una frontera.', 'La retirada se mide y fecha.'] }),
];
