import type { ReadingItem } from '../../types/curriculum';
import { OPEN_CELLS_CORE_SOURCES } from './sources';

type UnitSpec = readonly [number, string, string, string, string];

function unit([number, title, mentalModel, contract, mistake]: UnitSpec): ReadingItem {
  return {
    id: `open-cells-${String(number).padStart(2, '0')}-lectura`,
    type: 'reading',
    title,
    summary: mentalModel,
    estimatedMinutes: 14,
    sections: [
      { title: 'Modelo mental', content: mentalModel },
      {
        title: 'Contrato observable',
        content: contract,
        example: `Entrada: cambia una condición relevante para “${title}”.\nPredicción: ${contract}\nPrueba adversa: ${mistake}`,
        exampleCaption: 'Mini caso trabajado: entrada, predicción y prueba que podría refutarla.',
      },
      { title: 'Error común y cómo investigarlo', content: mistake },
    ],
    keyPoints: [contract, mistake, 'Explica la decisión con un ejemplo antes de memorizar la sintaxis.'],
    frequentQuestions: [
      { question: '¿Qué parte debo memorizar?', answer: 'Ninguna línea completa. Recuerda la responsabilidad, la entrada, la salida y cómo comprobar el contrato.' },
      { question: '¿Cómo practico sin copiar la respuesta?', answer: `Predice primero el resultado, cambia una sola causa y usa esta evidencia: ${contract}` },
    ],
    transferPrompt: `Aplica “${title}” a una aplicación de reservas: dibuja quién posee el dato, quién lo observa y qué evidencia confirmaría que el contrato funciona.`,
    sources: OPEN_CELLS_CORE_SOURCES,
  };
}

export const OPEN_CELLS_UNITS_07_TO_68: ReadingItem[] = ([
  [7, 'Anatomía del scaffold de componente', 'El scaffold es un mapa de responsabilidades, no una carpeta ceremonial: entrada pública, demo, locales, pruebas y documentación tienen consumidores distintos.', 'Puedes señalar qué archivo modificar para cambiar API, traducción, demo o metadata sin recorrer todo el proyecto.', 'Copiar código dentro de la demo en vez de consumir la entrada pública oculta errores de empaquetado; comprueba siempre el import que usaría otra aplicación.'],
  [8, 'WidgetMixin y su responsabilidad', 'WidgetMixin añade capacidades transversales de componente, especialmente traducción y emisión de eventos, sin decidir el aspecto ni el estado de negocio.', 'La clase usa this.t para texto visible y this.emitEvent para intenciones públicas; el render continúa siendo responsabilidad del componente.', 'Convertir el mixin en un almacén de estado global acopla instancias; revisa qué dato pertenece realmente al host.'],
  [9, 'Componer mixins sin romper super', 'Cada mixin envuelve una clase y coopera con la siguiente capa; super mantiene viva esa cadena de inicialización y ciclo.', 'Constructor y callbacks conservan super cuando la clase base lo requiere, y ninguna capa supone que es la única propietaria del ciclo.', 'Omitir super puede dejar capacidades parcialmente activas; aísla el fallo comprobando cada método aportado por los mixins.'],
  [10, 'Propiedades públicas y estado interno', 'Una propiedad pública es una entrada del componente; el estado interno describe cómo trabaja para producir una salida.', 'El consumidor puede configurar propiedades documentadas, mientras detalles de selección temporal o petición permanecen internos.', 'Exponer cada variable como propiedad crea una API accidental; pregunta si un consumidor necesita controlarla o solo observar el resultado.'],
  [11, 'disabled como contrato observable', 'disabled no es solo un color gris: bloquea interacción, comunica semántica accesible y evita emitir acciones.', 'Propiedad, atributo, control interno y evento mantienen el mismo estado; teclado y puntero observan el mismo bloqueo.', 'Cambiar únicamente CSS deja activo el comportamiento; intenta activar por teclado y escucha si todavía sale el evento.'],
  [12, 'Estados loading, empty, error y success', 'Una petición no produce solo datos: produce transiciones que la interfaz debe representar sin mezclar estados incompatibles.', 'En cada instante existe un estado principal y su información asociada; success tiene datos, empty confirma una respuesta válida sin elementos y error permite recuperación.', 'Usar una sola bandera loading suele dejar errores viejos junto a resultados nuevos; dibuja la tabla de transiciones antes de renderizar.'],
  [13, 'Slots, parts y tokens públicos', 'La personalización útil expone puntos deliberados: slots para contenido, parts para fragmentos y custom properties para decisiones de tema.', 'El componente documenta qué puede insertar o estilizar un consumidor sin atravesar su Shadow DOM.', 'Un selector profundo depende de estructura privada; cambia internamente el markup y comprueba que el contrato público siga estable.'],
  [14, 'SCSS fuente y CSS consumible', 'SCSS es material de autor; el navegador y el paquete consumen CSS. Ambos artefactos deben corresponder a la misma versión.', 'El build produce CSS determinista desde la fuente y el paquete exporta el artefacto que realmente usa la demo.', 'Editar solo el CSS generado pierde el cambio al recompilar; identifica siempre cuál archivo es fuente de verdad.'],

  [15, 'Por qué registrar dependencias localmente', 'Un host debe poder decidir qué clase implementa una etiqueta dentro de su árbol sin contaminar toda la página.', 'Las dependencias del template aparecen en scopedElements y no requieren customElements.define global desde el host.', 'Registrar todo globalmente funciona hasta que dos versiones compiten; prueba dos hosts con la misma etiqueta y clases distintas.'],
  [16, 'ScopedElementsMixin', 'ScopedElementsMixin conecta el registro local con el Shadow Root que renderiza Lit.', 'La clase compone el mixin una sola vez y entrega clases importadas mediante scopedElements.', 'Aplicar el mixin pero olvidar el registro produce etiquetas sin comportamiento; inspecciona primero la clase asociada al nombre local.'],
  [17, 'static get scopedElements()', 'scopedElements es una tabla nombre → clase, no una lista de strings ni una segunda importación.', 'Cada etiqueta usada por el template tiene una clase alcanzable y la clave coincide exactamente con el tag renderizado.', 'Una diferencia de un guion deja el elemento sin actualizar; compara tag, clave y export de clase como una cadena.'],
  [18, 'Importar clases sin registro global', 'Importar una clase obtiene su implementación; registrarla decide dónde puede resolverla el navegador. Son operaciones diferentes.', 'Los módulos de dependencias exportan clases consumibles y evitan efectos globales innecesarios.', 'Confundir import con registro oculta por qué una etiqueta no funciona; busca explícitamente quién posee el registro.'],
  [19, 'Dos hosts y una misma etiqueta', 'El aislamiento se demuestra cuando dos hosts resuelven la misma etiqueta a implementaciones distintas sin interferirse.', 'Cada host renderiza su versión, actualiza de forma independiente y no modifica customElements global.', 'Probar un solo host no demuestra aislamiento; monta ambos simultáneamente y compara constructor y salida.'],
  [20, 'Grafo de dependencias alcanzables', 'Un paquete debe declarar lo que importa directamente; el bundler calcula el grafo transitivo desde esas entradas.', 'package.json contiene dependencias directas mínimas y toda importación de producción se puede resolver desde ellas.', 'Añadir el catálogo entero enmascara imports accidentales; elimina una dependencia no usada y vuelve a construir demo y tests.'],
  [21, 'Import permitido frente a import arbitrario', 'El runtime browser usa una allowlist porque ejecutar un import equivale a conceder código y red a ese módulo.', 'Solo paquetes previstos, versiones fijadas y módulos locales normalizados entran al preview; lo demás falla con diagnóstico.', 'Aceptar cualquier URL hace irreproducible y riesgosa la práctica; prueba un paquete desconocido y exige un rechazo visible.'],
  [22, 'Diagnosticar una dependencia sin registrar', 'La etiqueta, el import y el registro forman tres eslabones; revisar los tres evita adivinar cambios.', 'El diagnóstico indica archivo y contrato faltante sin entregar la línea final de solución.', 'Cambiar HTML, import y registro a la vez borra evidencia; modifica un eslabón y vuelve a observar.'],

  [23, 'this.t y claves visibles', 'La interfaz pide significado mediante una clave; el catálogo decide la frase para el idioma activo.', 'Todo texto de producto usa claves estables, y una clave ausente se ve como error en vez de desaparecer.', 'Mezclar texto literal y traducido crea pantallas parcialmente localizadas; busca nodos visibles fuera de this.t.'],
  [24, 'Catálogos EN y ES completos', 'Los catálogos son dos implementaciones del mismo contrato de claves.', 'EN y ES contienen exactamente las mismas claves y cada valor pertenece al idioma correcto.', 'Contar entradas no basta si las claves difieren; compara conjuntos y reporta faltantes en ambos sentidos.'],
  [25, 'Placeholders como contrato', 'Un placeholder es un parámetro de la frase; su nombre también forma parte de la API de traducción.', 'Cada idioma conserva los mismos placeholders y this.t entrega todos los valores requeridos.', 'Traducir ${name} como ${nombre} rompe sustitución aunque la frase se entienda; compara nombres dentro de cada valor.'],
  [26, 'Inicialización y cambio de idioma', 'El idioma es estado de aplicación que debe estar listo antes de afirmar qué texto ve la persona.', 'El shell publica el cambio, los recursos terminan de cargar y los componentes actualizan sin recrear toda la app.', 'Afirmar inmediatamente después de cambiar idioma produce tests intermitentes; espera la señal de recursos listos.'],
  [27, 'Esperar recursos antes de comprobar texto', 'Una prueba asíncrona debe esperar la causa real —carga de catálogo y actualización Lit—, no un tiempo arbitrario.', 'La prueba aguarda la promesa o evento de idioma y luego updateComplete antes de leer el DOM.', 'Un setTimeout largo solo esconde carreras; reemplázalo por la condición observable que necesitas.'],
  [28, 'this.emitEvent', 'emitEvent convierte una acción interna en una intención pública nombrada desde el host.', 'El evento final incorpora el tag, viaja con bubbles y composed, y contiene un detail pequeño y estable.', 'Emitir click reexpone un gesto, no una decisión; nombra qué ocurrió en el dominio del componente.'],
  [29, 'detail, bubbles y composed', 'detail transporta el dato; bubbles permite ascender; composed permite cruzar Shadow DOM. Cada opción responde una frontera.', 'El consumidor escucha en una superficie estable y recibe solo la información necesaria para reaccionar.', 'Enviar la instancia completa en detail filtra estado privado; reconstruye un payload explícito con valores serializables.'],
  [30, 'Comunicación padre e hijo', 'El padre entrega datos mediante propiedades y el hijo devuelve intenciones mediante eventos; ninguno invade métodos privados del otro.', 'El flujo se puede dibujar como entrada descendente y evento ascendente sin referencias ocultas.', 'El padre que consulta shadowRoot para corregir al hijo depende de su implementación; prueba el mismo contrato con otro hijo.'],

  [31, 'Demo interactiva del componente', 'La demo es el consumidor humano más pequeño: configura entradas, escucha salidas y muestra estados importantes.', 'Puede probar propiedades, eventos y variantes sin editar el módulo del componente.', 'Una demo que replica lógica interna puede verse bien cuando el paquete está roto; importa siempre la entrada pública.'],
  [32, 'Pruebas de comportamiento público', 'Una buena prueba describe lo que cualquier consumidor puede hacer y observar.', 'Crea el tag, asigna entradas variadas, espera actualización, interactúa y comprueba DOM o eventos públicos.', 'Buscar una línea exacta rechaza soluciones equivalentes; prefiere valores diferentes y resultados observables.'],
  [33, 'Aislamiento y timeout de pruebas', 'Cada prueba necesita un DOM limpio y un límite de tiempo que convierta bloqueos en resultados diagnosticables.', 'El runner separa casos, restaura recursos y reporta qué promesa o evento no terminó.', 'Compartir instancias hace que el orden cambie el resultado; ejecuta el mismo caso solo y después dentro de la suite.'],
  [34, 'Coverage útil por archivo', 'Coverage señala qué código fue ejecutado; no demuestra por sí solo que el comportamiento sea correcto.', 'La interfaz diferencia cobertura de líneas y cobertura de contratos públicos, con archivos y denominadores visibles.', 'Celebrar 100% con aserciones débiles crea falsa seguridad; introduce un defecto y verifica que al menos una prueba falle.'],
  [35, 'Locales generados y divergencias', 'La generación ayuda a descubrir claves, pero una persona sigue decidiendo traducción y contexto.', 'El comando enumera claves usadas, conserva traducciones existentes y marca faltantes sin inventar frases definitivas.', 'Sobrescribir catálogos borra trabajo; compara antes y produce un cambio revisable.'],
  [36, 'Documentación y custom-elements.json', 'La documentación humana explica intención; el manifest ofrece una descripción estructurada a herramientas.', 'Nombre, propiedades, eventos, slots, parts y ejemplos coinciden entre código, README y custom-elements.json.', 'Generar metadata una vez y olvidarla crea una API fantasma; valida el manifest en cada build.'],
  [37, 'Build de demo y resolución de módulos', 'Construir es resolver un grafo desde entradas concretas y producir artefactos ejecutables, no concatenar archivos al azar.', 'Imports locales y permitidos se resuelven, rutas inválidas fallan y la demo ejecuta el mismo módulo que se exporta.', 'Un preview en blanco sin canal de errores deja al estudiante adivinando; comunica fallo, archivo y causa al host.'],
  [38, 'Exportar un componente consumible', 'La exportación es exitosa cuando otro proyecto puede instalar, importar y usar el paquete sin conocer el curso.', 'El ZIP conserva rutas, package.json, entrada, tipos, locales, tests, demo y metadata; una herramienta ZIP estándar lo valida.', 'Comprobar solo que existe un Blob no prueba el archivo; abre el ZIP y verifica CRC, nombres y contenido.'],

  [39, 'Crear una app Cells', 'Una app Cells coordina páginas, rutas, canales, configuración y servicios; no es un componente enorme con muchos if.', 'El scaffold separa app/scripts, pages, components, data, config, locales y tests con una entrada ejecutable.', 'Comenzar copiando una app completa oculta responsabilidades; recorre primero quién importa y quién llama cada pieza.'],
  [40, 'Workspace real de aplicación', 'El workspace es un proyecto exportable y versionado, no una colección de snippets sin relación.', 'La entrada, rutas y páginas forman un grafo resoluble; dev y prod conservan configuración explícita.', 'Guardar solo el archivo activo produce un ZIP incompleto; valida el snapshot entero antes de construir.'],
  [41, 'Configuración dev y prod', 'Configuración cambia valores de entorno; no debe cambiar las reglas de negocio ni exigir editar fuentes.', 'Cada entorno declara API, logging y flags esperados, y producción no hereda opciones de depuración.', 'Leer process.env dentro del navegador falla o se reemplaza tarde; importa una configuración generada y verificable.'],
  [42, 'Bootstrap del runtime público', 'El bootstrap recibe outlet, rutas e inicio; su trabajo es coordinar, no definir contenido de cada página.', 'Arranca una vez, publica contexto de aplicación y muestra un error observable si falta raíz o ruta inicial.', 'Iniciar el runtime desde varios módulos duplica listeners y navegación; localiza una única entrada.'],
  [43, 'CellsPageMixin', 'Una página es un componente enrutable con API de Bridge y ciclo de activación.', 'Su tag y clase terminan en -page, aplica CellsPageMixin y mantiene renderizado declarativo.', 'Usar el mixin en cada componente borra fronteras; resérvalo para superficies que participan en rutas y canales de app.'],
  [44, 'Páginas declarativas y lazy', 'La tabla de rutas describe qué página corresponde a cada nombre y cómo cargarla cuando se necesita.', 'Cada action devuelve un import dinámico y el componente declarado coincide con el tag definido por el módulo.', 'Importar todas las páginas al inicio contradice lazy loading; observa la red antes y después de navegar.'],
  [45, 'onPageEnter y parámetros', 'onPageEnter inicia trabajo cada vez que la página se vuelve activa y recibe los parámetros de navegación.', 'La página reinicia estado transitorio, valida params y comienza recursos que necesita para esa visita.', 'Usar constructor para params funciona solo la primera vez; navega dos veces a la misma página con ids distintos.'],
  [46, 'onPageLeave y cleanup', 'Salir de una página transfiere propiedad: aborta peticiones y elimina suscripciones antes de que otra página gobierne la pantalla.', 'Después de onPageLeave no llegan actualizaciones de canales ni respuestas de la visita anterior.', 'Ocultar el DOM no detiene trabajo; publica después de salir y comprueba que la página vieja permanece inmóvil.'],

  [47, 'Definir rutas y nombres', 'path pertenece a la URL; name es el identificador estable que usa navigate; component es el tag que se renderiza.', 'Cada ruta tiene las tres piezas coherentes y solo una ruta notFound.', 'Navegar usando el path donde la API espera name rompe alias y cambios futuros; prueba un path alternativo para la misma página.'],
  [48, 'Navegación imperativa', 'navigate expresa una intención desde una página o Bridge; no debe filtrarse hacia componentes puramente visuales.', 'La página traduce el evento del hijo a navigate con un nombre conocido y parámetros explícitos.', 'Una tarjeta que importa el router deja de ser reutilizable; muévela a otra página y comprueba que aún funciona.'],
  [49, 'Parámetros de ruta', 'Los parámetros son entrada de la visita, no estado global permanente.', 'La ruta identifica campos, navigate los entrega y onPageEnter valida ausencia, tipo y valor.', 'Confiar en que id siempre existe crea pantallas vacías; ensaya navegación sin id y una ruta desconocida.'],
  [50, 'Evento, canal o navegación', 'Evento comunica dentro de un árbol cercano; canal desacopla participantes de aplicación; navegación cambia página.', 'La elección se justifica por distancia, duración y propietario del dato, no por comodidad de sintaxis.', 'Publicar cada click en un canal global crea tráfico sin significado; nombra la decisión y limita su alcance.'],
  [51, 'Publicar y suscribirse', 'Un canal es un conducto nombrado con un último valor; publicar cambia ese valor y notifica observadores.', 'Productor y suscriptor acuerdan nombre, forma del payload y momento de creación.', 'Dos nombres casi iguales crean canales distintos sin error; centraliza contratos y prueba extremo a extremo.'],
  [52, 'Payloads estables', 'El payload de canal es una API entre partes que pueden evolucionar por separado.', 'Contiene datos serializables, versión o forma documentada y evita instancias privadas.', 'Enviar un elemento DOM permite mutaciones invisibles; copia los valores de negocio que realmente necesita el receptor.'],
  [53, 'Estado retenido', 'Un nuevo suscriptor recibe el último valor del canal; eso convierte orden temporal en una decisión de producto.', 'La prueba cubre publicar antes de suscribir y confirma una única entrega inicial con el valor más reciente.', 'Suponer que solo llegan eventos futuros duplica cargas; ensaya siempre la suscripción tardía.'],
  [54, 'Desuscripción y ausencia posterior', 'Cleanup se demuestra por lo que deja de ocurrir: ninguna entrega después de abandonar la página.', 'unsubscribe corta callbacks del host sin borrar el canal para consumidores válidos.', 'Comprobar solo que se llamó unsubscribe no demuestra efecto; publica después y observa el contador del callback.'],

  [55, 'Cells Bridge como mediador', 'Bridge conecta páginas y aplicación mediante contratos sin hacer que cada componente conozca a todos los demás.', 'publish, subscribe, navigate y contexto están disponibles solo donde la arquitectura los necesita.', 'Convertir Bridge en un contenedor de cualquier variable recrea un estado global opaco; asigna propietario y duración.'],
  [56, 'Eventos externos y canales', 'Un adaptador recibe un evento externo, valida su payload y publica una forma interna estable.', 'La frontera traduce nombres y datos una sola vez y permite sustituir el origen externo.', 'Reenviar el evento completo acopla la app al proveedor; prueba con un segundo origen equivalente.'],
  [57, 'Data manager separado', 'El data manager posee transporte, cancelación y transformación; la página posee presentación y navegación.', 'La página observa estados públicos del manager sin construir URLs ni interpretar respuestas crudas.', 'Un manager que navega o pinta DOM mezcla capas; reemplaza la página por una prueba y verifica que sigue usable.'],
  [58, 'Transiciones de una petición', 'Una petición es una máquina de estados: idle → loading → success, empty o error, con retry y cancelación posibles.', 'Cada transición limpia datos incompatibles y produce una salida observable única.', 'Actualizar error sin retirar loading deja dos verdades; usa una tabla de estado y revisa cada salida.'],
  [59, 'Loading y empty', 'Loading significa que todavía no hay decisión; empty significa que terminó correctamente y no hay elementos.', 'La interfaz distingue ambas situaciones y ofrece mensajes o acciones apropiadas.', 'Mostrar “sin resultados” mientras carga confunde lentitud con ausencia; prueba una promesa controlable.'],
  [60, 'Error recuperable', 'Un error útil explica qué falló, conserva contexto seguro y ofrece una acción posible como reintentar.', 'Retry crea una petición nueva, limpia el error anterior y no duplica suscripciones.', 'Capturar y no emitir el error produce un spinner eterno; fuerza un rechazo y sigue la transición completa.'],
  [61, 'Cancelación y respuestas fuera de orden', 'Abortar reduce trabajo, pero un requestId también impide que una respuesta antigua gane si no pudo cancelarse.', 'La última solicitud es la única autorizada para publicar success, empty o error.', 'Probar solo una petición no expone carreras; resuelve dos promesas en orden inverso.'],
  [62, 'Cleanup del data manager', 'Al salir, la página corta tanto la fuente de datos como la ruta que entregaría sus resultados.', 'disconnect aborta la petición activa y no se publica ningún estado posterior a onPageLeave.', 'Eliminar el elemento sin abortar permite que un callback retenga memoria; observa listeners y señales después del desmontaje.'],

  [63, 'Tests de aplicación', 'Una prueba de app recorre una historia vertical: página inicial, evento de hijo, canal, navegación, parámetros y cleanup.', 'El runner monta un outlet aislado y comprueba resultados visibles además de contratos intermedios.', 'Probar piezas verdes por separado no garantiza integración; rompe el nombre de ruta y exige que el flujo falle.'],
  [64, 'Locales de aplicación', 'El shell decide idioma y las páginas consumen el mismo contrato de recursos sin duplicar catálogos por componente.', 'Cambio de idioma actualiza la página activa y una página lazy carga su texto correcto al entrar después.', 'Precargar solo la página inicial deja huecos al navegar; prueba una ruta que todavía no se había importado.'],
  [65, 'Build con configuración de producción', 'El build de producción fija entorno, resuelve rutas y elimina capacidades de depuración sin cambiar comportamiento público.', 'El artefacto arranca desde cero, carga páginas lazy y no contiene secretos ni URLs de desarrollo.', 'Un build exitoso puede estar mal configurado; inspecciona el artefacto y ejecuta un smoke real.'],
  [66, 'Seguridad de iframe, Worker e imports', 'Código editable vive detrás de fronteras: Worker para transformación y tests; iframe sandbox para UI; allowlist para paquetes.', 'No hay acceso a fs, procesos, sockets ni origen del host, y los errores cruzan por mensajes validados.', 'Añadir allow-same-origin junto con allow-scripts debilita el sandbox; revisa permisos como una lista mínima.'],
  [67, 'Paridad entre browser y CLI', 'La plataforma no necesita ejecutar Node para conservar contratos de archivos, comandos y resultados compatibles.', 'Fixtures compartidas producen el mismo scaffold esperado y cada diferencia se clasifica como soportada o bloqueante.', 'Comparar solo nombres de archivo omite semántica; valida imports, scripts, API, demo, tests y metadata.'],
  [68, 'Exportación y continuación fuera de la plataforma', 'El curso termina cuando el proyecto sale del navegador y continúa como una app Cells comprensible, no cuando una barra llega a 100%.', 'El ZIP abre con herramientas estándar, instala dependencias declaradas, ejecuta tests y conserva decisiones documentadas.', 'Entregar sin un recorrido limpio desde cero deja estado oculto; descomprime en una carpeta nueva y repite build, test y navegación.'],
] as UnitSpec[]).map(unit);

const appCleanup = OPEN_CELLS_UNITS_07_TO_68.find((item) => item.id === 'open-cells-46-lectura');
if (appCleanup) {
  appCleanup.handsOnLab = 'open-cells-app-playground';
  appCleanup.estimatedMinutes = 40;
}

const channelsPractice = OPEN_CELLS_UNITS_07_TO_68.find((item) => item.id === 'open-cells-54-lectura');
if (channelsPractice) {
  channelsPractice.handsOnLab = 'open-cells-channels-playground';
  channelsPractice.estimatedMinutes = 40;
}

const dataPractice = OPEN_CELLS_UNITS_07_TO_68.find((item) => item.id === 'open-cells-62-lectura');
if (dataPractice) {
  dataPractice.handsOnLab = 'open-cells-data-playground';
  dataPractice.estimatedMinutes = 40;
}

const deliveryPractice = OPEN_CELLS_UNITS_07_TO_68.find((item) => item.id === 'open-cells-68-lectura');
if (deliveryPractice) {
  deliveryPractice.handsOnLab = 'open-cells-delivery-playground';
  deliveryPractice.estimatedMinutes = 40;
}
