import { ScrimLessonData } from '../../types/scrim';

type Profile = Required<Pick<ScrimLessonData, 'mentalModel' | 'frequentQuestions' | 'representations' | 'transferPrompt' | 'masteryChecks'>>;

function profile(mentalModel: string, question: string, answer: string, representations: string[], transferPrompt: string, masteryChecks: string[]): Profile {
  return {
    mentalModel,
    frequentQuestions: [
      { question, answer },
      { question: '¿Cómo compruebo que no estoy adivinando?', answer: 'Predice primero una salida concreta, ejecuta un ejemplo mínimo y compara. Si no coincide, sigue el estado una instrucción a la vez.' },
      { question: '¿Debo memorizar toda la sintaxis ahora?', answer: 'No. Debes reconocer las piezas, saber qué problema resuelven y consultar la forma exacta cuando la necesites.' },
    ],
    representations,
    transferPrompt,
    masteryChecks,
  };
}

export const PEDAGOGICAL_PROFILE_BY_LESSON: Record<string, Profile> = {
  'fundamentos-01': profile('Un programa es una fila de instrucciones exactas que se ejecutan en orden.', '¿Por qué no aparece nada?', 'Comprueba que llamaste a console.log con paréntesis y que el texto está entre comillas; nombrar la herramienta no la ejecuta.', ['secuencia vertical'], '¿Qué tres mensajes usarías para describir el inicio de tu día?', ['Escribe dos llamadas válidas.', 'Predice el orden de la consola.']),
  'fundamentos-02': profile('Programar empieza por transformar una meta en pasos que otra persona podría seguir sin preguntar.', '¿Por qué un plan correcto produce un resultado incorrecto?', 'La sintaxis puede ser válida y el orden lógico estar mal. Recorre la secuencia de arriba abajo y verifica la dependencia entre pasos.', ['pseudocódigo', 'entrada-proceso-salida'], 'Divide “registrar un libro prestado” en entrada, proceso y salida.', ['Ordena una secuencia.', 'Distingue meta de instrucción.']),
  'fundamentos-03': profile('Una variable es un nombre asociado con un valor que puede permanecer o cambiar.', '¿Cuándo uso let y cuándo const?', 'Usa const si no reasignarás la variable y let si ese nombre recibirá otro valor durante el programa.', ['tabla de estado'], 'Representa nombre, intentos y sesión activa en una tabla de estado.', ['Distingue string, number y boolean.', 'Predice una reasignación.']),
  'fundamentos-04': profile('Una expresión es una pequeña máquina: recibe valores y produce un nuevo valor.', '¿Por qué “5” + 2 da un resultado extraño?', 'Las comillas crean texto. Antes de operar, identifica el tipo de cada valor y el tipo que esperas producir.', ['árbol de expresión', 'tabla verdadero-falso'], 'Escribe la expresión que decide si una compra tiene envío gratis.', ['Calcula una expresión.', 'Explica qué booleano produce una comparación.']),
  'fundamentos-05': profile('Una condición es una bifurcación: solo uno de los caminos encadenados debe ganar.', '¿Por qué nunca llega a mi segundo caso?', 'En else if gana la primera condición verdadera. Ordena de lo más específico a lo más general y revisa los límites.', ['diagrama de flujo', 'tabla de decisión'], 'Diseña las decisiones para clasificar una temperatura.', ['Traza el camino de un dato.', 'Prueba valores límite.']),
  'fundamentos-06': profile('Un bucle repite una acción mientras un contador o condición avance hacia el final.', '¿Por qué se repite una vez de más?', 'Compara inicio, operador de límite y paso. Con índices suele recorrerse desde 0 mientras i sea menor que length.', ['tabla de iteraciones'], 'Traza las vueltas necesarias para contar tres intentos.', ['Completa una tabla de vueltas.', 'Detecta un bucle que no termina.']),
  'fundamentos-07': profile('Una función es una caja con contrato: entradas claras, una responsabilidad y una salida predecible.', '¿Por qué obtengo undefined?', 'La función llegó al final sin ejecutar return, o estás usando el resultado de una función que solo produce un efecto.', ['caja entrada-salida', 'diagrama de llamada'], 'Define el contrato de una función que calcula el precio final.', ['Distingue definir de llamar.', 'Explica parámetros y retorno.']),
  'fundamentos-08': profile('Un array es una fila ordenada de datos; el índice indica la casilla y length cuántas casillas hay.', '¿Por qué lista[lista.length] es undefined?', 'Los índices comienzan en cero, por eso la última posición es length - 1.', ['fila indexada', 'tabla de recorrido'], 'Representa una lista de puntuaciones con índices.', ['Accede al primer y último elemento.', 'Recorre sin salir del array.']),
  'fundamentos-09': profile('Un objeto es una ficha cuyos campos tienen nombre y significado.', '¿Cuándo uso objeto y cuándo array?', 'Usa objeto para describir una cosa mediante propiedades; array para una colección ordenada de cosas.', ['ficha de propiedades'], 'Modela un evento con nombre, fecha y cupos.', ['Lee y modifica propiedades.', 'Justifica objeto frente a array.']),
  'fundamentos-10': profile('El DOM es el mapa de objetos que el navegador construye a partir del HTML.', '¿Por qué getElementById devuelve null?', 'El id no existe todavía o no coincide exactamente. Verifica el HTML y que el script se ejecute después de crear el elemento.', ['árbol DOM'], 'Dibuja el árbol simplificado de una tarjeta con título y botón.', ['Localiza un elemento.', 'Cambia una propiedad visible.']),
  'fundamentos-11': profile('Un evento es un aviso futuro que conecta una acción de la persona con una función.', '¿Por qué mi función se ejecuta al cargar?', 'Probablemente escribiste responder() al registrar el listener. Entrega responder sin paréntesis para que el navegador la llame después.', ['evento-función-cambio'], 'Representa el flujo de pulsar un botón para abrir un menú.', ['Conecta un listener.', 'Distingue entregar de llamar.']),
  'fundamentos-12': profile('Una interacción completa mueve un dato desde la entrada, por una regla, hasta una salida.', '¿Por qué siempre leo el valor anterior?', 'Lee input.value dentro del evento, justo cuando ocurre la acción, y después transforma y muestra el dato.', ['entrada-proceso-salida'], 'Dibuja el flujo para convertir kilómetros a millas.', ['Lee el valor actual.', 'Separa entrada, proceso y salida.']),
  'fundamentos-13': profile('Renderizar es traducir una colección de datos a elementos visibles.', '¿Por qué aparecen filas duplicadas?', 'Si vuelves a dibujar sin limpiar el contenedor, agregas otra copia. Decide si actualizas una fila o reconstruyes desde cero.', ['datos-a-vista', 'tabla índice-elemento'], 'Explica cómo mostrarías una lista de compras.', ['Crea una fila por dato.', 'Evita duplicados al renderizar.']),
  'fundamentos-14': profile('El estado es la verdad del programa; la interfaz es una representación que puede reconstruirse desde él.', '¿Por qué pantalla y datos dicen cosas distintas?', 'Alguna acción cambió solo uno de los dos. Actualiza primero el estado y luego llama a una única función de render.', ['datos-lógica-interfaz'], 'Describe el estado y render de un contador de hábitos.', ['Separa regla y render.', 'Construye una interacción completa.']),
  'fundamentos-15': profile('Depurar es reducir incertidumbre con evidencia: reproducir, aislar, explicar, cambiar y verificar.', '¿Qué cambio primero cuando no funciona?', 'Nada todavía. Escribe qué esperabas, reproduce el fallo y encuentra la primera observación que contradice tu modelo.', ['ciclo de depuración', 'línea de evidencia'], 'Aplica el ciclo a una lámpara que no enciende.', ['Formula una hipótesis comprobable.', 'Verifica que el arreglo no rompa otro caso.']),
  'fundamentos-16': profile('Un método es una operación ofrecida por un valor; su contrato dice argumentos, retorno y si modifica el receptor.', '¿Qué diferencia hay entre función, método y propiedad?', 'Una función se llama por su nombre, un método pertenece a un receptor y una propiedad se lee sin paréntesis.', ['firma de contrato', 'receptor-método-retorno'], 'Compara la firma de toUpperCase, includes y push.', ['Lee una firma.', 'Predice mutación y retorno.']),
  'fundamentos-17': profile('Pseudocódigo y diagramas son mapas de decisiones antes de elegir sintaxis.', '¿Cuál hago primero?', 'Empieza por entrada, salida y reglas en palabras. Usa diagrama si hay caminos; tabla si necesitas seguir cambios.', ['pseudocódigo', 'diagrama de flujo'], 'Modela la decisión de aceptar una reserva.', ['Convierte requisito en pasos.', 'Conecta caminos sí/no.']),
  'fundamentos-18': profile('Muchos algoritmos son una sola pasada que conserva un estado parcial: contador, suma, mínimo o máximo.', '¿Cómo sé qué variable necesito?', 'Pregunta qué debes recordar después de cada elemento. Ese recuerdo es el acumulador o candidato actual.', ['tabla de seguimiento', 'invariante cotidiana'], 'Traza paso a paso una suma de gastos de varios días y explica qué recuerda el acumulador.', ['Elige estado inicial.', 'Explica cada actualización.']),
  'fundamentos-19': profile('Buscar responde uno; filtrar selecciona varios; transformar produce una versión nueva de cada elemento.', '¿Debo usar for o un método?', 'Elige por claridad y contrato. Un for explícito ayuda a aprender el flujo; un método expresa la intención cuando entiendes su callback.', ['tabla intención-resultado', 'flujo de colección'], 'Elige operación para nombres aprobados y etiquetas en mayúsculas.', ['Distingue find/filter/map.', 'Justifica el resultado esperado.']),
  'fundamentos-20': profile('Una prueba es un ejemplo elegido para atacar una suposición, no solo para confirmar el caso feliz.', '¿Qué pruebo si ya funciona?', 'Prueba el límite, la entrada vacía, un dato inválido y un caso diferente al que usaste al programar.', ['tabla de casos', 'particiones de entrada'], 'Diseña casos para una regla de descuento.', ['Incluye normal, límite e inválido.', 'Explica qué fallo detecta cada caso.']),
  'fundamentos-21': profile('El flujo de datos cuenta quién cambia el estado y quién solo lo representa.', '¿Dónde debe vivir el dato?', 'En una fuente de verdad explícita. Los eventos solicitan cambios; las reglas producen estado; render lo muestra.', ['estado-transición-vista', 'flujo unidireccional'], 'Dibuja el flujo de marcar una tarea completada.', ['Identifica fuente de verdad.', 'Evita cambios paralelos de estado y DOM.']),
  'fundamentos-22': profile('Un módulo reúne responsabilidades relacionadas y expone una frontera pequeña a otros archivos.', '¿Cómo sé qué archivo debe contener una función?', 'Ponla junto a los datos o reglas que conoce. Si necesita DOM, pertenece a interfaz; si calcula sin DOM, pertenece a reglas.', ['mapa de dependencias', 'interfaz pública'], 'Divide una calculadora de gastos en datos, reglas e interfaz.', ['Evita dependencia circular.', 'Exporta solo lo necesario.']),
  'fundamentos-23': profile('Arquitectura es decidir responsabilidades y dirección de dependencias para que el cambio tenga un lugar claro.', '¿Necesito un patrón con nombre?', 'No. Empieza por estado, reglas, coordinación e interfaz; comprueba que las reglas puedan probarse sin abrir la página.', ['capas simples', 'mapa de dependencias'], 'Propón arquitectura para un registro de lecturas.', ['Explica cada flecha.', 'Aísla reglas del DOM.']),
  'fundamentos-24': profile('Un proyecto se construye por cortes verificables: requisito, modelo, regla, interacción y prueba.', '¿Por dónde empiezo una app completa?', 'Elige una historia pequeña y completa. Define el dato y un caso de prueba antes de conectar la interfaz.', ['requisitos-modelo-flujo-arquitectura'], 'Explica qué cambiarías para convertir el planificador en una app de hábitos.', ['Implementa sin sintaxis nueva.', 'Prueba reglas y flujo DOM.', 'Explica decisiones.']),
};
