import { ReasoningConnection, ReasoningExerciseItem, ReasoningNode } from '../../types/curriculum';

function base(lesson: number, title: string, activity: ReasoningExerciseItem['activity'], explanation: string): ReasoningExerciseItem {
  const relatedLessonId = `javascript-${String(lesson).padStart(2, '0')}`;
  return {
    id: `${relatedLessonId}-reasoning`, title, type: 'reasoning', relatedLessonId, estimatedMinutes: 6,
    description: 'Representa el problema y comprueba tu predicción antes de volver al editor.', activity,
    hints: [
      { level: 1, text: 'Nombra la entrada, el estado que cambia y la salida esperada.' },
      { level: 2, text: 'Traza un caso pequeño sin saltar pasos.' },
      { level: 3, text: 'Cada paso solo puede usar información que ya existe.' },
    ],
    explanation,
  };
}

const sequence = (lesson: number, title: string, prompt: string, steps: ReasoningNode[], expectedOrder: string[]) => base(lesson, title, { kind: 'sequence', prompt, steps, expectedOrder }, 'El orden correcto conserva las dependencias entre entrada, transformación y salida.');
const trace = (lesson: number, title: string, prompt: string, columns: string[], rows: ReasoningNode[], expectedCells: Record<string, string>) => base(lesson, title, { kind: 'trace-table', prompt, columns, rows, expectedCells }, 'La tabla muestra el valor después de cada paso y revela la primera diferencia con la predicción.');
const decision = (lesson: number, title: string, prompt: string, cases: Array<ReasoningNode & { options: string[] }>, expectedOutcomes: Record<string, string>) => base(lesson, title, { kind: 'decision-table', prompt, cases, expectedOutcomes }, 'Cada fila representa un grupo de entradas; los límites pertenecen al camino que define el contrato.');
const flow = (lesson: number, title: string, prompt: string, nodes: Array<ReasoningNode & { role: 'start' | 'process' | 'decision' | 'output' | 'end' }>, expectedConnections: ReasoningConnection[], distractors: ReasoningConnection[] = []) => base(lesson, title, { kind: 'flowchart', prompt, nodes, connectionOptions: [...expectedConnections, ...distractors], expectedConnections }, 'Las flechas forman un recorrido completo y cada decisión conserva sus salidas posibles.');
const dependencies = (lesson: number, title: string, prompt: string, modules: ReasoningNode[], expectedDependencies: ReasoningConnection[], distractors: ReasoningConnection[] = []) => base(lesson, title, { kind: 'dependency-map', prompt, modules, dependencyOptions: [...expectedDependencies, ...distractors], expectedDependencies }, 'La dirección correcta deja las reglas independientes de los detalles de interfaz y red.');

export const JAVASCRIPT_REASONING: ReasoningExerciseItem[] = [
  sequence(1, 'Ordena la ejecución', 'Ordena lo que ocurre al mostrar un mensaje.', [{ id: 'salida', label: 'El mensaje aparece en la consola' }, { id: 'leer', label: 'JavaScript lee la llamada completa' }, { id: 'llamar', label: 'console.log recibe el texto' }], ['leer', 'llamar', 'salida']),
  trace(2, 'Sigue una reasignación', 'Completa el valor de nivel después de cada instrucción.', ['nivel'], [{ id: 'crear', label: 'let nivel = 1' }, { id: 'cambiar', label: 'nivel = 2' }], { 'crear.nivel': '1', 'cambiar.nivel': '2' }),
  trace(3, 'Sigue tipos y operaciones', 'Completa el valor después de convertir y multiplicar.', ['valor'], [{ id: 'texto', label: 'entrada = "5"' }, { id: 'numero', label: 'Number(entrada)' }, { id: 'calculo', label: 'resultado * 60' }], { 'texto.valor': '"5"', 'numero.valor': '5', 'calculo.valor': '300' }),
  decision(4, 'Construye los caminos', 'Clasifica las fronteras de temperatura.', [{ id: '9', label: '9 grados', options: ['frío', 'templado', 'calor'] }, { id: '10', label: '10 grados', options: ['frío', 'templado', 'calor'] }, { id: '25', label: '25 grados', options: ['frío', 'templado', 'calor'] }], { '9': 'frío', '10': 'templado', '25': 'calor' }),
  sequence(5, 'Sigue una llamada', 'Ordena cada paso que ocurre al ejecutar precioConImpuesto(100, 0.2).', [{ id: 'devolver', label: 'return entrega 120' }, { id: 'entrar', label: 'Los argumentos entran en los parámetros' }, { id: 'impuesto', label: 'El impuesto calculado es 20' }], ['entrar', 'impuesto', 'devolver']),
  trace(6, 'Traza el acumulador', 'Sigue cómo cambia la variable total mientras el bucle suma los números del 1 al 3.', ['total'], [{ id: 'uno', label: 'Después de sumar 1' }, { id: 'dos', label: 'Después de sumar 2' }, { id: 'tres', label: 'Después de sumar 3' }], { 'uno.total': '1', 'dos.total': '3', 'tres.total': '6' }),
  dependencies(7, 'Dibuja los alcances', 'Selecciona qué función puede usar cada nombre.', [{ id: 'global', label: 'configuración global' }, { id: 'calcular', label: 'calcular(precio)' }, { id: 'formatear', label: 'formatear(valor)' }], [{ from: 'calcular', to: 'global', label: 'puede leer' }, { from: 'formatear', to: 'global', label: 'puede leer' }], [{ from: 'calcular', to: 'formatear', label: 'lee variable local' }]),
  sequence(8, 'Investiga un método', 'Ordena los pasos para investigar y comprobar por tu cuenta el método startsWith.', [{ id: 'probar', label: 'Probar un caso mínimo propio' }, { id: 'necesidad', label: 'Definir que necesitas un booleano sobre el comienzo' }, { id: 'contrato', label: 'Leer receptor, argumento y retorno' }], ['necesidad', 'contrato', 'probar']),
  trace(9, 'Relaciona índice y length', 'Completa los datos de ["a", "b", "c"].', ['valor'], [{ id: 'primero', label: 'lista[0]' }, { id: 'cantidad', label: 'lista.length' }, { id: 'ultimo', label: 'lista[lista.length - 1]' }], { 'primero.valor': 'a', 'cantidad.valor': '3', 'ultimo.valor': 'c' }),
  decision(10, 'Elige el método por su salida', 'Relaciona la necesidad con map, filter o find.', [{ id: 'dobles', label: 'Un doble por elemento', options: ['map', 'filter', 'find'] }, { id: 'pares', label: 'Conservar números pares', options: ['map', 'filter', 'find'] }, { id: 'primero', label: 'Primer nombre corto', options: ['map', 'filter', 'find'] }], { dobles: 'map', pares: 'filter', primero: 'find' }),
  dependencies(11, 'Modela una ficha', 'Conecta la entidad con sus propiedades.', [{ id: 'producto', label: 'producto' }, { id: 'nombre', label: 'nombre' }, { id: 'precio', label: 'precio' }], [{ from: 'producto', to: 'nombre', label: 'propiedad' }, { from: 'producto', to: 'precio', label: 'propiedad' }]),
  dependencies(12, 'Dibuja referencias y copias', 'Selecciona qué nombres observan el mismo objeto.', [{ id: 'original', label: 'original' }, { id: 'alias', label: 'alias = original' }, { id: 'copia', label: 'copia = { ...original }' }], [{ from: 'alias', to: 'original', label: 'misma referencia' }], [{ from: 'copia', to: 'original', label: 'misma referencia' }]),
  flow(13, 'Conecta JavaScript con el DOM', 'Forma el flujo para mostrar un saludo.', [{ id: 'inicio', label: 'Ejecutar script', role: 'start' }, { id: 'buscar', label: 'Buscar #salida', role: 'process' }, { id: 'escribir', label: 'Asignar textContent', role: 'process' }, { id: 'visible', label: 'Texto visible', role: 'end' }], [{ from: 'inicio', to: 'buscar' }, { from: 'buscar', to: 'escribir' }, { from: 'escribir', to: 'visible' }], [{ from: 'inicio', to: 'escribir' }]),
  flow(14, 'Dibuja un evento', 'Conecta el clic con el cambio visible.', [{ id: 'espera', label: 'Esperar', role: 'start' }, { id: 'clic', label: 'Ocurre click', role: 'process' }, { id: 'estado', label: 'Cambiar estado', role: 'process' }, { id: 'vista', label: 'Actualizar vista', role: 'end' }], [{ from: 'espera', to: 'clic' }, { from: 'clic', to: 'estado' }, { from: 'estado', to: 'vista' }], [{ from: 'espera', to: 'vista' }]),
  flow(15, 'Dibuja un render', 'Conecta los datos con cada paso necesario hasta obtener una lista visible y actualizada.', [{ id: 'datos', label: 'Array de tareas', role: 'start' }, { id: 'limpiar', label: 'Limpiar contenedor', role: 'process' }, { id: 'crear', label: 'Crear un li por dato', role: 'process' }, { id: 'lista', label: 'Lista visible', role: 'end' }], [{ from: 'datos', to: 'limpiar' }, { from: 'limpiar', to: 'crear' }, { from: 'crear', to: 'lista' }], [{ from: 'lista', to: 'datos' }]),
  sequence(16, 'Ordena la depuración', 'Ordena un ciclo que conserve evidencia.', [{ id: 'verificar', label: 'Comprobar el caso y una regresión' }, { id: 'reproducir', label: 'Reproducir y anotar esperado/observado' }, { id: 'cambiar', label: 'Cambiar una sola causa' }, { id: 'hipotesis', label: 'Formular una hipótesis' }], ['reproducir', 'hipotesis', 'cambiar', 'verificar']),
  sequence(17, 'Sigue la persistencia', 'Ordena cómo guardar y recuperar un perfil.', [{ id: 'parse', label: 'JSON.parse reconstruye datos' }, { id: 'stringify', label: 'JSON.stringify produce texto' }, { id: 'guardar', label: 'localStorage guarda el texto' }, { id: 'leer', label: 'localStorage devuelve el texto' }], ['stringify', 'guardar', 'leer', 'parse']),
  sequence(18, 'Predice el bucle de eventos', 'Ordena la salida de inicio, temporizador cero y fin.', [{ id: 'tarea', label: 'La callback muestra “tarea”' }, { id: 'inicio', label: 'Se muestra “inicio”' }, { id: 'fin', label: 'Se muestra “fin”' }], ['inicio', 'fin', 'tarea']),
  flow(19, 'Dibuja una promesa', 'Conecta una operación asíncrona con éxito o error.', [{ id: 'inicio', label: 'Llamar operación', role: 'start' }, { id: 'esperar', label: 'await Promise', role: 'process' }, { id: 'ok', label: '¿Se cumplió?', role: 'decision' }, { id: 'dato', label: 'Usar dato', role: 'output' }, { id: 'error', label: 'Manejar error', role: 'output' }, { id: 'fin', label: 'Terminar', role: 'end' }], [{ from: 'inicio', to: 'esperar' }, { from: 'esperar', to: 'ok' }, { from: 'ok', to: 'dato', label: 'sí' }, { from: 'ok', to: 'error', label: 'no' }, { from: 'dato', to: 'fin' }, { from: 'error', to: 'fin' }]),
  flow(20, 'Dibuja una petición HTTP', 'Ordena la validación de una respuesta.', [{ id: 'inicio', label: 'fetch URL', role: 'start' }, { id: 'response', label: 'Recibir Response', role: 'process' }, { id: 'ok', label: '¿response.ok?', role: 'decision' }, { id: 'json', label: 'Leer JSON', role: 'output' }, { id: 'error', label: 'Lanzar error', role: 'output' }, { id: 'fin', label: 'Terminar', role: 'end' }], [{ from: 'inicio', to: 'response' }, { from: 'response', to: 'ok' }, { from: 'ok', to: 'json', label: 'sí' }, { from: 'ok', to: 'error', label: 'no' }, { from: 'json', to: 'fin' }, { from: 'error', to: 'fin' }]),
  dependencies(21, 'Diseña módulos sin círculos', 'Selecciona dependencias que mantienen las reglas puras.', [{ id: 'ui', label: 'interfaz.js' }, { id: 'reglas', label: 'reglas.js' }, { id: 'datos', label: 'datos.js' }], [{ from: 'ui', to: 'reglas', label: 'importa' }, { from: 'ui', to: 'datos', label: 'importa' }, { from: 'reglas', to: 'datos', label: 'usa' }], [{ from: 'reglas', to: 'ui', label: 'importa DOM' }]),
  dependencies(22, 'Separa instancias', 'Conecta cada nombre con su estado propio.', [{ id: 'clase', label: 'Clase Contador' }, { id: 'a', label: 'instancia a' }, { id: 'b', label: 'instancia b' }], [{ from: 'a', to: 'clase', label: 'comparte métodos' }, { from: 'b', to: 'clase', label: 'comparte métodos' }], [{ from: 'a', to: 'b', label: 'comparte estado' }]),
  flow(23, 'Dibuja el ciclo del componente', 'Conecta registro, creación y conexión.', [{ id: 'registro', label: 'customElements.define', role: 'start' }, { id: 'crear', label: 'El navegador crea la etiqueta', role: 'process' }, { id: 'conectar', label: 'connectedCallback', role: 'process' }, { id: 'vista', label: 'Componente visible', role: 'end' }], [{ from: 'registro', to: 'crear' }, { from: 'crear', to: 'conectar' }, { from: 'conectar', to: 'vista' }]),
  sequence(24, 'Planifica el corte vertical', 'Ordena el primer incremento del proyecto final.', [{ id: 'ui', label: 'Conectar evento y render' }, { id: 'regla', label: 'Modelar datos y regla pura' }, { id: 'casos', label: 'Definir casos normal, límite e inválido' }, { id: 'historia', label: 'Elegir una historia pequeña y observable' }], ['historia', 'regla', 'casos', 'ui']),
];

export const JAVASCRIPT_REASONING_BY_LESSON: Record<string, ReasoningExerciseItem> = Object.fromEntries(
  JAVASCRIPT_REASONING.map((item) => [item.relatedLessonId, item]),
);
