import { JavaScriptLessonSpec } from './types';

const MDN = 'MDN Web Docs';
const source = (title: string, url: string, purpose: string) => ({ title, url, publisher: MDN, purpose });
const consoleTest = (id: string, description: string, expectedContains: string[]) => ({ id, description, validatorType: 'console-check' as const, expectedContains });
const fn = (id: string, description: string, targetFunction: string, args: unknown[], expectedReturn: unknown) => ({ id, description, validatorType: 'function-call' as const, targetFunction, args, expectedReturn });

export const JAVASCRIPT_SPECS_01_TO_08: JavaScriptLessonSpec[] = [
  {
    number: 1, module: 1, title: 'Cómo lee JavaScript tu programa', summary: 'Escribe instrucciones válidas, predice su orden y usa la consola como primera evidencia.',
    concepts: [{ label: 'Instrucción', desc: 'Una orden completa que el motor puede interpretar y ejecutar.' }, { label: 'Consola', desc: 'Una salida de diagnóstico donde puedes observar valores sin construir una interfaz.' }],
    skillsRequired: [], skillsIntroduced: ['javascript-syntax', 'console-output'],
    script: [
      'JavaScript no adivina lo que quieres decir. Lee símbolos concretos, forma una instrucción y la ejecuta. Hoy no construiremos una página compleja: primero aprenderemos a producir una salida que podamos comprobar.',
      'En console.log, console es la herramienta y log es una operación de esa herramienta. Los paréntesis contienen el valor que queremos mostrar. El texto va entre comillas porque, sin ellas, JavaScript buscaría un nombre.',
      'Mira el archivo de arriba abajo. La primera llamada muestra “Inicio” y la segunda muestra “Listo”. Si intercambiamos las líneas, también cambia la salida. La consola nos deja verificar esa predicción.',
      'Ahora escribe dos mensajes tuyos. Conserva la forma completa de cada llamada y comprueba que aparecen en el mismo orden. El reto evalúa la salida, no una frase de código memorizada.',
    ],
    example: 'console.log("Inicio");\nconsole.log("Listo");\n', starter: '// Muestra primero tu nombre y después una meta de aprendizaje.\n',
    challengeTitle: 'Dos mensajes en orden', challengeInstructions: 'Muestra en la consola un mensaje que contenga “Nombre:” y después otro que contenga “Meta:”. Puedes elegir el contenido.',
    tests: [consoleTest('js01-name', 'La salida identifica un nombre', ['Nombre:']), consoleTest('js01-goal', 'La salida identifica una meta', ['Meta:'])],
    hints: ['Cada salida usa una llamada completa a console.log.', 'El texto debe estar dentro de los paréntesis y entre comillas.', 'Ejecuta y mira la consola: deben aparecer dos líneas, en ese orden.'],
    reading: {
      definition: 'Una instrucción es una orden ejecutable. Una llamada usa un nombre, paréntesis y, a veces, argumentos. console.log recibe valores y los muestra como ayuda para observar el programa.',
      secondExample: 'console.log("Uno");\nconsole.log("Dos");', walkthrough: 'La primera línea termina antes de que empiece la segunda. La consola conserva ese orden.',
      investigation: 'En MDN busca “console.log”. Localiza el apartado de sintaxis, identifica qué valores acepta y prueba el ejemplo más pequeño en la consola del navegador.',
      commonErrors: 'Olvidar comillas hace que el texto parezca un nombre de variable. Olvidar cerrar paréntesis impide interpretar la instrucción completa.',
      keyPoints: ['El archivo se ejecuta de arriba abajo', 'El texto lleva comillas', 'Los argumentos van entre paréntesis', 'La consola aporta evidencia'],
      questions: [{ question: '¿El punto y coma es obligatorio?', answer: 'JavaScript puede insertarlo en muchos casos, pero usarlo al comenzar hace visible dónde termina la instrucción.' }, { question: '¿console.log forma parte del resultado final?', answer: 'Suele usarse para observar y depurar. Más adelante escribirás también en la página.' }],
      transfer: 'Escribe tres mensajes que describan el inicio de tu día y predice el orden antes de ejecutar.', sources: [source('console.log()', 'https://developer.mozilla.org/es/docs/Web/API/console/log_static', 'Lee la sintaxis y observa que puede recibir uno o varios valores.')],
    },
    debug: { title: 'La segunda llamada quedó abierta', expected: 'La consola muestra “Preparar” y “Ejecutar”.', observed: 'Un error de sintaxis evita que se ejecute el archivo.', starter: 'console.log("Preparar");\nconsole.log("Ejecutar";\n', tests: [consoleTest('js01-d1', 'Muestra el primer paso', ['Preparar']), consoleTest('js01-d2', 'Muestra el segundo paso', ['Ejecutar'])], hints: ['Compara los símbolos que abren y cierran la segunda llamada.', 'El texto ya tiene sus dos comillas.', 'Revisa el paréntesis que debe aparecer antes del punto y coma.'] },
  },
  {
    number: 2, module: 1, title: 'Valores, tipos y variables', summary: 'Asocia nombres con valores, distingue tipos primitivos y decide cuándo usar const o let.',
    concepts: [{ label: 'Valor y tipo', desc: 'Un dato concreto y la clase de operaciones que tiene sentido aplicar sobre él.' }, { label: 'const y let', desc: 'Nombres asociados a valores; let permite reasignar y const no.' }],
    skillsRequired: ['javascript-syntax', 'console-output'], skillsIntroduced: ['variables', 'primitive-types', 'reassignment'],
    script: [
      'Un programa necesita recordar datos. Una variable nos permite asociar un nombre con un valor para usarlo después. Por ahora piensa en esa asociación: JavaScript mantiene el valor disponible mientras el programa se ejecuta.',
      'Usa const cuando ese nombre no recibirá otro valor. Usa let cuando la historia del programa exige reasignarlo. El tipo pertenece al valor: “Ana” es texto, 18 es número y true es booleano.',
      'Aquí puntos empieza en diez y luego recibe doce. nombre permanece igual. Al mostrar ambos valores, podemos seguir el estado sin imaginarlo. Reasignar no crea una segunda variable; cambia el valor asociado al mismo nombre.',
      'En el reto elige nombres claros y representa tres tipos. Una de las variables debe cambiar. No copies el ejemplo: piensa qué dato de tu propio perfil permanecería y cuál podría actualizarse.',
    ],
    example: 'const nombre = "Lina";\nlet puntos = 10;\npuntos = 12;\nconsole.log(nombre);\nconsole.log(puntos);\n', starter: '// Crea un texto, un número que pueda cambiar y un booleano.\n',
    challengeTitle: 'Un perfil con estado', challengeInstructions: 'Crea nombre como texto, nivel como número y disponible como booleano. Reasigna nivel a 2 y muestra los tres valores.',
    tests: [consoleTest('js02-name', 'Muestra un nombre', ['2']), consoleTest('js02-state', 'El nivel actualizado aparece junto con el booleano', ['true'])],
    hints: ['Piensa primero qué nombres permanecen y cuál cambia.', 'El texto usa comillas; número y booleano no.', 'La reasignación escribe solo el nombre, el signo igual y el valor nuevo.'],
    reading: {
      definition: 'Una variable es un nombre asociado a un valor. String, number, boolean, undefined y null son valores primitivos frecuentes. const evita reasignar el nombre; let la permite.',
      secondExample: 'const ciudad = "Cali";\nlet intentos = 0;\nintentos = 1;\nconsole.log(ciudad, intentos);', walkthrough: 'ciudad sigue apuntando al mismo texto. intentos cambia de cero a uno antes de llegar a la consola.',
      investigation: 'En la guía “Gramática y tipos” busca declaraciones, tipos de datos y conversión. Para una duda concreta, ejecuta typeof sobre un valor pequeño.',
      commonErrors: 'Escribir comillas alrededor de un número crea texto. Intentar reasignar const produce un error. Declarar de nuevo con let no es lo mismo que reasignar.',
      keyPoints: ['El tipo pertenece al valor', 'const no se reasigna', 'let permite reasignación', 'Los nombres claros explican el estado'],
      questions: [{ question: '¿Dónde se guarda el valor?', answer: 'El motor reserva memoria internamente. JavaScript no expone una dirección que debas manipular. Veremos referencias después de objetos y arrays.' }, { question: '¿Debo usar let para todo?', answer: 'No. Empieza con const y cambia a let solo cuando el nombre deba recibir otro valor.' }],
      transfer: 'Representa el estado de un reproductor: canción, volumen y si está pausado. Decide cuál puede cambiar.', sources: [source('Gramática y tipos', 'https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Grammar_and_types', 'Consulta declaraciones, tipos y conversión sin intentar memorizar toda la guía.'), source('Tipos de datos y estructuras', 'https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Data_structures', 'Distingue valores primitivos de objetos.')],
    },
    debug: { title: 'El contador no puede cambiar', expected: 'El contador pasa de uno a dos.', observed: 'La reasignación de una constante lanza un error.', starter: 'const contador = 1;\ncontador = 2;\nconsole.log(contador);\n', tests: [consoleTest('js02-d1', 'El contador actualizado llega a la consola', ['2']), { id: 'js02-d2', description: 'La variable admite reasignación', validatorType: 'source-regex', regexPattern: 'let\\s+contador' }], hints: ['El valor debe cambiar durante el programa.', '¿Qué declaración permite reasignar?', 'Cambia la palabra de declaración, no el número final.'] },
  },
  {
    number: 3, module: 1, title: 'Operadores y conversiones explícitas', summary: 'Construye expresiones, compara con igualdad estricta y convierte datos cuando el contrato lo exige.',
    concepts: [{ label: 'Expresión', desc: 'Una combinación de valores y operadores que produce otro valor.' }, { label: 'Conversión explícita', desc: 'Transformar de forma visible texto a número o número a texto.' }],
    skillsRequired: ['variables', 'primitive-types', 'reassignment'], skillsIntroduced: ['operators', 'strict-equality', 'explicit-conversion'],
    script: ['Una expresión toma valores y produce otro. Antes de escribirla, nombra el tipo de entrada y el tipo de salida. Esa pregunta evita muchos resultados sorprendentes.', 'El signo más suma números, pero concatena si participa texto. Por eso convertimos de forma explícita con Number cuando recibimos dígitos escritos. Para comparar usamos triple igual y evitamos conversiones ocultas.', 'En el ejemplo cantidad llega como texto. Number produce el número tres; después la multiplicación produce doce. La comparación estricta confirma que el resultado es un número con valor doce.', 'Tu reto recibe otro texto numérico. Convierte primero y calcula después. Prueba también un dato distinto para asegurarte de que no escribiste la respuesta fija.'],
    example: 'const precio = 4;\nconst cantidadEscrita = "3";\nconst cantidad = Number(cantidadEscrita);\nconst total = precio * cantidad;\nconsole.log(total);\nconsole.log(total === 12);\n', starter: 'const minutosEscritos = "5";\n// Convierte y calcula cuántos segundos son.\n',
    challengeTitle: 'De minutos a segundos', challengeInstructions: 'Convierte minutosEscritos a número, calcula los segundos y muestra 300 en la consola.', tests: [consoleTest('js03-c1', 'Calcula trescientos segundos', ['300']), { id: 'js03-c2', description: 'La conversión es explícita', validatorType: 'source-regex', regexPattern: 'Number\\s*\\(' }], hints: ['La entrada tiene comillas: comienza como string.', 'Number recibe el texto y devuelve un número.', 'Un minuto contiene sesenta segundos.'],
    reading: { definition: 'Una expresión produce un valor. Los operadores aritméticos calculan; los comparadores producen booleanos. Number, String y Boolean permiten conversiones visibles.', secondExample: 'const edad = Number("20");\nconst puedeEntrar = edad >= 18;\nconsole.log(puedeEntrar);', walkthrough: 'Number devuelve veinte. La comparación mayor o igual produce true.', investigation: 'Busca cada operador en “Expresiones y operadores”. En una conversión, consulta qué devuelve con una entrada válida y qué ocurre con una inválida.', commonErrors: 'Usar + con texto puede concatenar. == convierte tipos de forma implícita. Number de un texto no numérico produce NaN.', keyPoints: ['Predice tipos de entrada y salida', '=== no convierte tipos', 'Convierte en la frontera', 'Prueba datos distintos'], questions: [{ question: '¿Por qué no usar ==?', answer: 'Porque puede convertir valores antes de compararlos. === expresa una comparación más predecible.' }, { question: '¿Qué es NaN?', answer: 'Es un valor numérico especial que indica que una conversión o cálculo no produjo un número válido.' }], transfer: 'Convierte una temperatura escrita y calcula su equivalente en Fahrenheit.', sources: [source('Expresiones y operadores', 'https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Expressions_and_operators', 'Consulta por familias: asignación, aritmética, comparación y lógica.'), source('Number()', 'https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Number/Number', 'Observa entradas, retorno y casos que producen NaN.') ] },
    debug: { title: 'El total quedó pegado como texto', expected: 'Diez más cinco produce quince.', observed: 'La consola muestra 105.', starter: 'const base = 10;\nconst extra = "5";\nconst total = base + extra;\nconsole.log(total);\n', tests: [consoleTest('js03-d1', 'El total es quince', ['15']), { id: 'js03-d2', description: 'La entrada se convierte de forma visible', validatorType: 'source-regex', regexPattern: 'Number\\s*\\(' }], hints: ['Anota el tipo de base y el tipo de extra.', 'El operador + concatena si uno de los valores es texto.', 'Convierte extra antes de sumarlo.'] },
  },
  {
    number: 4, module: 1, title: 'Decisiones con if y operadores lógicos', summary: 'Convierte reglas en caminos exclusivos y prueba sus fronteras.',
    concepts: [{ label: 'Condición', desc: 'Una expresión booleana que decide si un bloque se ejecuta.' }, { label: 'Frontera', desc: 'El valor exacto donde una regla cambia de resultado.' }], skillsRequired: ['operators', 'strict-equality', 'explicit-conversion'], skillsIntroduced: ['conditionals', 'logical-operators', 'boundaries'],
    script: ['Una condición convierte una regla en una pregunta que solo puede responder true o false. Antes de escribir llaves, enumera las salidas posibles.', 'if recorre el primer camino cuya condición sea verdadera. else cubre lo que queda. Con && exigimos dos reglas a la vez; con || basta una. No combines condiciones hasta poder decirlas en voz alta.', 'La función del ejemplo acepta una compra desde cincuenta, pero solo si hay inventario. Cuarenta y nueve marca la frontera inferior; cincuenta debe aceptarse.', 'En tu reto hay tres salidas. Decide primero qué ocurre debajo, exactamente en el límite y por encima. Después traduce ese mapa a código.'],
    example: 'function puedeComprar(total, hayInventario) {\n  if (total >= 50 && hayInventario) {\n    return "aceptada";\n  }\n  return "rechazada";\n}\nconsole.log(puedeComprar(50, true));\n', starter: 'function clasificarTemperatura(grados) {\n  // Menos de 10: "frío". De 10 a 24: "templado". Desde 25: "calor".\n}\n', challengeTitle: 'Tres rangos de temperatura', challengeInstructions: 'Completa clasificarTemperatura sin cambiar su nombre ni parámetro.', tests: [fn('js04-c1', 'Clasifica nueve', 'clasificarTemperatura', [9], 'frío'), fn('js04-c2', 'Respeta los límites', 'clasificarTemperatura', [25], 'calor')], hints: ['Dibuja tres salidas y prueba 9, 10, 24 y 25.', 'Pregunta primero por el rango más bajo o el más alto.', 'Cada camino debe devolver exactamente una etiqueta.'],
    reading: { definition: 'if ejecuta un bloque cuando su condición es verdadera. else if añade preguntas ordenadas y else cubre el resto. &&, || y ! combinan o invierten booleanos.', secondExample: 'function tarifa(edad) {\n  if (edad < 12) return "infantil";\n  if (edad >= 65) return "mayor";\n  return "general";\n}', walkthrough: 'Con once sale por el primer return. Con setenta falla la primera condición y cumple la segunda. Con treinta llega al retorno final.', investigation: 'En “Control de flujo” busca if...else. Escribe una tabla de casos antes de copiar sintaxis. Para operadores lógicos, prueba combinaciones de true y false.', commonErrors: 'Ordenar primero una condición demasiado amplia vuelve inalcanzable otra. Confundir < con <= rompe el caso límite.', keyPoints: ['Cada condición produce booleano', 'El orden de caminos importa', 'Prueba las fronteras', 'else cubre lo restante'], questions: [{ question: '¿Necesito else después de return?', answer: 'No siempre. return termina la función, por lo que puedes continuar con otra condición sin anidar.' }, { question: '¿&& y || devuelven siempre booleanos?', answer: 'En JavaScript devuelven operandos según su veracidad. En este nivel úsalos con comparaciones booleanas explícitas.' }], transfer: 'Diseña una regla de envío con total mínimo y zona admitida.', sources: [source('Control de flujo y manejo de errores', 'https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Control_flow_and_error_handling', 'Lee if...else y prueba cada camino con una tabla.'), source('Operadores lógicos', 'https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Operators/Logical_AND', 'Observa evaluación corta y valor de retorno.') ] },
    debug: { title: 'La mayoría de edad rechaza el límite', expected: 'Dieciocho y diecinueve se aceptan.', observed: 'Dieciocho se rechaza por usar una comparación estricta.', starter: 'function puedeRegistrarse(edad) {\n  if (edad > 18) return true;\n  return false;\n}\n', tests: [fn('js04-d1', 'Acepta el límite', 'puedeRegistrarse', [18], true), fn('js04-d2', 'Sigue rechazando debajo', 'puedeRegistrarse', [17], false)], hints: ['Escribe la regla con palabras: “desde dieciocho”.', 'Prueba exactamente el límite.', 'La comparación debe incluir igualdad.'] },
  },
  {
    number: 5, module: 2, title: 'Funciones como contratos', summary: 'Declara funciones con parámetros, devuelve resultados y separa cálculo de salida.', concepts: [{ label: 'Parámetro', desc: 'Nombre local que representa un dato que llegará al llamar la función.' }, { label: 'return', desc: 'Entrega el resultado y termina esa ejecución de la función.' }], skillsRequired: ['conditionals', 'logical-operators', 'boundaries'], skillsIntroduced: ['functions', 'parameters', 'return-values'],
    script: ['Una función empaqueta una tarea con nombre. Su firma actúa como contrato: dice qué datos necesita y la llamada entrega argumentos concretos.', 'Los parámetros son nombres locales. return devuelve el resultado a quien llamó y termina esa ejecución. console.log solo muestra; no sustituye el valor devuelto.', 'areaRectangulo recibe ancho y alto. La función no conoce el ejemplo cinco por tres: aplica la misma regla a cualquier par válido.', 'En tu reto escribe una función pura. Primero prueba el cálculo con papel. Después usa dos entradas distintas para confirmar que ambos parámetros participan.'],
    example: 'function areaRectangulo(ancho, alto) {\n  return ancho * alto;\n}\nconst area = areaRectangulo(5, 3);\nconsole.log(area);\n', starter: 'function precioConImpuesto(precio, tasa) {\n  // Devuelve el precio más el impuesto.\n}\n', challengeTitle: 'Precio final reutilizable', challengeInstructions: 'Completa precioConImpuesto. La tasa llega como proporción: 0.2 significa veinte por ciento.', tests: [fn('js05-c1', 'Calcula veinte por ciento', 'precioConImpuesto', [100, 0.2], 120), fn('js05-c2', 'Usa otros argumentos', 'precioConImpuesto', [50, 0.1], 55)], hints: ['Escribe qué representa cada parámetro.', 'El impuesto es precio multiplicado por tasa.', 'Devuelve precio más impuesto; no fijes el resultado de un ejemplo.'],
    reading: { definition: 'Una función recibe argumentos mediante parámetros, ejecuta una tarea y puede devolver un valor. Una función pura depende de sus entradas y no modifica la pantalla.', secondExample: 'function convertirHoras(minutos) {\n  return minutos / 60;\n}\nconsole.log(convertirHoras(90));', walkthrough: 'minutos recibe noventa. La división produce uno y medio. return entrega ese número a console.log.', investigation: 'En la guía de funciones identifica declaración, parámetros, argumentos y retorno. Al investigar una función desconocida, anota firma, retorno y efectos.', commonErrors: 'Confundir mostrar con devolver deja undefined para quien necesita el resultado. Ignorar un parámetro suele esconder una respuesta fijada al ejemplo.', keyPoints: ['La firma expresa un contrato', 'Argumento y parámetro no son lo mismo', 'return entrega el resultado', 'Prueba varios datos'], questions: [{ question: '¿Puede una función no devolver nada?', answer: 'Sí. En ese caso su retorno es undefined. Algunas funciones existen por un efecto, como actualizar una interfaz.' }, { question: '¿Cuántos parámetros convienen?', answer: 'Los necesarios para expresar una responsabilidad clara. Muchos parámetros pueden indicar que la tarea es demasiado grande.' }], transfer: 'Diseña la firma de una función que calcule el costo de entradas para varias personas.', sources: [source('Funciones', 'https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Functions', 'Distingue declaración, llamada, parámetros y valor devuelto.') ] },
    debug: { title: 'La función muestra pero no devuelve', expected: 'doble(4) devuelve 8 y doble(7) devuelve 14.', observed: 'La función imprime un resultado, pero quien la llama recibe undefined.', starter: 'function doble(numero) {\n  console.log(numero * 2);\n}\n', tests: [fn('js05-d1', 'Devuelve ocho', 'doble', [4], 8), fn('js05-d2', 'Generaliza a siete', 'doble', [7], 14)], hints: ['La prueba usa el valor que recibe quien llama.', 'console.log no entrega el dato a la llamada.', 'Usa la palabra que devuelve un resultado.'] },
  },
  {
    number: 6, module: 2, title: 'Repetición y seguimiento de estado', summary: 'Usa bucles cuando una regla se repite y sigue el valor de control en una tabla.', concepts: [{ label: 'Bucle', desc: 'Una estructura que repite un bloque mientras se cumpla una condición.' }, { label: 'Iteración', desc: 'Una vuelta completa del bloque repetido.' }], skillsRequired: ['functions', 'parameters', 'return-values'], skillsIntroduced: ['loops', 'iteration', 'accumulators'],
    script: ['Un bucle evita copiar la misma instrucción muchas veces. Pero antes de escribirlo debes responder tres preguntas: dónde empieza, cuándo continúa y cómo avanza.', 'En un for, la inicialización ocurre una vez. La condición se revisa antes de cada vuelta y el avance ocurre después. Una tabla con índice y acumulador hace visible el recorrido.', 'El ejemplo suma uno, dos y tres. total empieza en cero y conserva lo acumulado. En cada vuelta añadimos el valor actual.', 'Tu reto cuenta, no suma. El contador cambia solo cuando el número cumple la regla. Prueba una lista de valores escrita en el propio bucle sin usar arrays todavía.'],
    example: 'let total = 0;\nfor (let numero = 1; numero <= 3; numero++) {\n  total = total + numero;\n}\nconsole.log(total);\n', starter: 'function contarParesHasta(limite) {\n  let cantidad = 0;\n  // Recorre desde 1 hasta limite e incrementa cuando sea par.\n  return cantidad;\n}\n', challengeTitle: 'Cuenta pares hasta un límite', challengeInstructions: 'Completa contarParesHasta con un bucle. Debe incluir el límite si es par.', tests: [fn('js06-c1', 'Cuenta hasta seis', 'contarParesHasta', [6], 3), fn('js06-c2', 'Respeta otro límite', 'contarParesHasta', [9], 4)], hints: ['La variable del bucle comienza en uno y avanza de uno en uno.', 'Un número par tiene resto cero al dividir entre dos.', 'Incrementa cantidad solo dentro de esa condición.'],
    reading: { definition: 'Un bucle repite un bloque. for reúne inicio, condición y avance. Un acumulador conserva un resumen de las vueltas anteriores.', secondExample: 'let producto = 1;\nfor (let n = 1; n <= 4; n++) {\n  producto = producto * n;\n}\nconsole.log(producto);', walkthrough: 'producto toma 1, luego 2, luego 6 y por último 24. La tabla de estado muestra cada cambio.', investigation: 'En “Bucles e iteración” compara for y while. Para cada uno identifica inicio, condición y avance; evita elegir por costumbre.', commonErrors: 'Una condición que nunca se vuelve falsa crea un bucle infinito. Empezar un contador en uno rompe el caso sin coincidencias.', keyPoints: ['Define inicio, condición y avance', 'Traza valores pequeños', 'El acumulador empieza con identidad adecuada', 'Prueba cero y el límite'], questions: [{ question: '¿Cuándo uso while?', answer: 'Cuando la cantidad de vueltas depende de una condición y no de un contador claro. for suele ser más legible para recorridos contados.' }, { question: '¿Qué hace ++?', answer: 'Incrementa un número en uno. Aquí se usa como avance del contador.' }], transfer: 'Cuenta cuántos múltiplos de tres existen hasta un límite.', sources: [source('Bucles e iteración', 'https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Loops_and_iteration', 'Compara estructuras y reconoce sus condiciones de salida.') ] },
    debug: { title: 'El recorrido olvida el límite', expected: 'sumarHasta(3) devuelve 6.', observed: 'El bucle solo suma uno y dos.', starter: 'function sumarHasta(limite) {\n  let total = 0;\n  for (let n = 1; n < limite; n++) {\n    total = total + n;\n  }\n  return total;\n}\n', tests: [fn('js06-d1', 'Incluye tres', 'sumarHasta', [3], 6), fn('js06-d2', 'Incluye cinco', 'sumarHasta', [5], 15)], hints: ['Traza el valor exacto del límite.', 'La condición se revisa antes de cada vuelta.', 'El contrato dice “hasta e incluyendo”.'] },
  },
  {
    number: 7, module: 2, title: 'Alcance y vida de los nombres', summary: 'Reconoce dónde existe una variable y evita depender de estado global oculto.', concepts: [{ label: 'Alcance', desc: 'La zona del código donde un nombre puede usarse.' }, { label: 'Variable local', desc: 'Un nombre creado dentro de una función o bloque y aislado de fuera.' }], skillsRequired: ['loops', 'iteration', 'accumulators'], skillsIntroduced: ['scope', 'local-variables'],
    script: ['Un nombre no existe en todos los lugares. Su alcance depende de dónde se declara. Esta frontera evita que funciones distintas pisen datos por accidente.', 'Los parámetros y las variables creadas dentro de una función son locales. let y const también respetan los bloques entre llaves. Desde fuera no puedes leerlas directamente.', 'En el ejemplo cada llamada crea su propio subtotal. precio e impuesto existen durante esa llamada y desaparecen de nuestro alcance cuando termina.', 'Tu reto debe depender solo de parámetros y variables locales. Si la función necesita un dato, ponlo en la firma en vez de leer una variable global escondida.'],
    example: 'function calcular(precio, tasa) {\n  const impuesto = precio * tasa;\n  const subtotal = precio + impuesto;\n  return subtotal;\n}\nconsole.log(calcular(20, 0.1));\n', starter: 'const descuentoGlobal = 5;\nfunction precioFinal(precio, descuento) {\n  // Usa solo los parámetros de la función.\n}\n', challengeTitle: 'Una función sin dependencia oculta', challengeInstructions: 'Completa precioFinal para restar el parámetro descuento al precio. No uses descuentoGlobal.', tests: [fn('js07-c1', 'Resta el descuento recibido', 'precioFinal', [30, 4], 26), fn('js07-c2', 'No depende del valor global', 'precioFinal', [10, 2], 8)], hints: ['La firma ya contiene los dos datos necesarios.', 'Una variable global no debe decidir el resultado.', 'Devuelve la operación entre precio y descuento.'],
    reading: { definition: 'El alcance determina dónde puede resolverse un nombre. Los parámetros viven dentro de la función. let y const creados en un bloque no salen de ese bloque.', secondExample: 'function etiqueta(nombre) {\n  const prefijo = "Hola";\n  return prefijo + ", " + nombre;\n}', walkthrough: 'prefijo y nombre existen durante la llamada. El texto devuelto sí puede salir.', investigation: 'En MDN busca “Ámbito de función” y “Ámbito de bloque”. Dibuja cajas alrededor de llaves y marca dónde nace cada nombre.', commonErrors: 'Leer o modificar una variable global hace que una función dependa de contexto oculto. Declarar dentro de if y usar fuera produce un error de referencia.', keyPoints: ['El lugar de declaración define el alcance', 'Parámetros son locales', 'Evita dependencias globales', 'Devuelve datos para sacarlos de la función'], questions: [{ question: '¿La variable se borra al terminar?', answer: 'Una variable local deja de ser accesible. El motor administra su memoria; más adelante veremos cierres y recolección.' }, { question: '¿Puedo repetir un nombre en otra función?', answer: 'Sí. Cada función tiene su propio alcance y esos nombres no se mezclan.' }], transfer: 'Reescribe una función que usa un impuesto global para recibirlo como parámetro.', sources: [source('Ámbitos y cierres', 'https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Functions#%C3%A1mbito_de_una_funci%C3%B3n', 'Identifica qué nombres puede resolver cada función.') ] },
    debug: { title: 'La función usa el descuento equivocado', expected: 'El resultado depende del argumento descuento.', observed: 'Siempre usa diez por la variable externa.', starter: 'const descuento = 10;\nfunction aplicar(precio, descuentoPedido) {\n  return precio - descuento;\n}\n', tests: [fn('js07-d1', 'Usa descuento cuatro', 'aplicar', [20, 4], 16), fn('js07-d2', 'Usa descuento uno', 'aplicar', [20, 1], 19)], hints: ['Compara el parámetro con la variable de fuera.', 'El contrato ya entrega el descuento correcto.', 'Usa el nombre local descuentoPedido.'] },
  },
  {
    number: 8, module: 2, title: 'Métodos de string y lectura de documentación', summary: 'Lee métodos como contratos y transforma texto sin confundir propiedades, llamadas y mutación.', concepts: [{ label: 'Método', desc: 'Una función disponible a través de un valor u objeto receptor.' }, { label: 'String inmutable', desc: 'Los métodos producen otro texto; no cambian el string original.' }], skillsRequired: ['scope', 'local-variables'], skillsIntroduced: ['string-methods', 'method-contracts', 'documentation-reading'],
    script: ['Un método es una función que se llama desde un receptor. En texto.trim(), el texto aparece antes del punto y trim es la operación disponible para ese valor.', 'Para aprender un método no memorices una lista. Pregunta qué recibe, qué devuelve y si modifica el original. Los strings son inmutables: sus métodos producen un texto nuevo.', 'El ejemplo limpia espacios, convierte a minúsculas y después pregunta si comienza con una palabra. Cada retorno alimenta la siguiente llamada.', 'En tu reto aplicarás startsWith, que acabamos de usar. La función debe aceptar variaciones de mayúsculas y espacios sin cambiar el argumento original.'],
    example: 'const entrada = "  JavaScript Claro  ";\nconst normalizada = entrada.trim().toLowerCase();\nconst comienzaConJs = normalizada.startsWith("javascript");\nconsole.log(normalizada);\nconsole.log(comienzaConJs);\n', starter: 'function esComandoGuardar(texto) {\n  // Acepta textos como "  GUARDAR archivo".\n}\n', challengeTitle: 'Normaliza antes de comparar', challengeInstructions: 'Completa esComandoGuardar. Quita espacios exteriores, ignora mayúsculas y devuelve true si el texto comienza con “guardar”.', tests: [fn('js08-c1', 'Acepta espacios y mayúsculas', 'esComandoGuardar', ['  GUARDAR archivo'], true), fn('js08-c2', 'Rechaza otro comando', 'esComandoGuardar', ['borrar archivo'], false)], hints: ['Construye primero un texto normalizado.', 'trim y toLowerCase devuelven nuevos strings.', 'startsWith pregunta por el comienzo y devuelve booleano.'],
    reading: { definition: 'Un método se llama desde un receptor. length es una propiedad; trim(), includes() y startsWith() son métodos. Los métodos de string devuelven valores nuevos.', secondExample: 'const correo = "  ANA@EJEMPLO.COM ";\nconst limpio = correo.trim().toLowerCase();\nconsole.log(limpio.endsWith(".com"));', walkthrough: 'trim devuelve texto sin bordes, toLowerCase devuelve minúsculas y endsWith devuelve un booleano.', investigation: 'En una página de método busca: sintaxis, parámetros, retorno y ejemplos. Escribe luego un caso mínimo propio. Investiga trim, includes, startsWith, endsWith, slice y replace según la necesidad.', commonErrors: 'length no lleva paréntesis. Olvidar guardar el retorno deja el texto original intacto. includes distingue mayúsculas.', keyPoints: ['Identifica el receptor', 'Distingue propiedad y método', 'Lee el retorno', 'Strings no se mutan'], questions: [{ question: '¿Por qué puedo llamar métodos si string es primitivo?', answer: 'JavaScript ofrece operaciones de String mediante una envoltura temporal. Para usarlo basta pensar que el tipo define métodos disponibles.' }, { question: '¿Debo encadenar siempre?', answer: 'No. Variables intermedias ayudan a leer y depurar. Encadena solo cuando cada retorno está claro.' }], transfer: 'Normaliza un nombre de usuario y comprueba si termina en un sufijo permitido.', sources: [source('String', 'https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/String', 'Explora métodos por la forma de salida que necesitas.'), source('String.prototype.trim()', 'https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/String/trim', 'Lee retorno e inmutabilidad antes de usarlo.') ] },
    debug: { title: 'La extensión distingue mayúsculas', expected: 'FOTO.JPG y foto.jpg se reconocen.', observed: 'Solo funciona la versión en minúsculas.', starter: 'function esJpg(nombre) {\n  return nombre.endsWith(".jpg");\n}\n', tests: [fn('js08-d1', 'Acepta minúsculas', 'esJpg', ['foto.jpg'], true), fn('js08-d2', 'Acepta mayúsculas', 'esJpg', ['FOTO.JPG'], true)], hints: ['El método distingue mayúsculas.', 'Normaliza el receptor antes de preguntar.', 'toLowerCase devuelve un texto nuevo que puedes encadenar.'] },
  },
];
