import { existsSync } from 'node:fs';
import { chromium, expect } from '@playwright/test';
import { createOpenCellsLessonWorkspace } from '../src/curriculum/open-cells/lessonWorkspaces';
import { buildCellsPreviewDocument } from '../src/engine/cells/cellsPreviewCompiler';

const browser = await chromium.launch({ executablePath: existsSync('/opt/google/chrome/chrome') ? '/opt/google/chrome/chrome' : undefined, headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } });
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  const exportedUrl = process.env.CELLS_RETENTION_APP_URL;
  if (exportedUrl) await page.goto(exportedUrl);
  else {
    await page.setContent('<iframe title="Aplicación" sandbox="allow-scripts" style="width:100%;height:950px;border:0"></iframe>');
    await page.locator('iframe').evaluate((frame: HTMLIFrameElement, html) => { frame.srcdoc = html; }, buildCellsPreviewDocument(createOpenCellsLessonWorkspace(77).snapshot).html);
  }
  const app = exportedUrl ? page : page.frameLocator('iframe');
  const home = app.locator('academy-home-page');
  await expect(home).toBeVisible();
  await expect(home.getByRole('heading', { level: 1 })).toHaveText('Estudio Cells');
  await expect(home.getByRole('button', { name: 'Carrito', exact: true })).toHaveCount(0);
  await expect(home.locator('academy-product-card').first()).not.toContainText('€');
  const first = await home.elementHandle();
  const draft = home.getByLabel('Borrador local de esta página');
  await draft.fill('Nota que debe sobrevivir');
  await home.getByRole('button', { name: 'Guardar nota fuera de la página', exact: true }).click();
  await draft.fill('Borrador solo de esta instancia');
  await home.locator('academy-product-card').first().getByRole('button').click();
  const detail = app.locator('academy-product-detail-page');
  await expect(detail).toBeVisible();
  expect(await first!.evaluate((node) => node.isConnected)).toBe(true);
  await expect(home).not.toBeVisible();
  await detail.getByRole('button').click();
  await expect(home).toBeVisible();
  await expect(draft).toHaveValue('Borrador solo de esta instancia');
  await expect(home.locator('[data-retained-pages]')).toHaveText('2');
  await expect(home.locator('[data-retained-listeners]')).toHaveText('2');
  await home.getByRole('button', { name: 'Enviar evento a las páginas retenidas', exact: true }).click();
  await expect(home.locator('[data-retention-pulses]')).toHaveText('1');
  await home.getByRole('button', { name: 'Guardados', exact: true }).click();
  const favorites = app.locator('academy-favorites-page');
  await expect(favorites).toBeVisible();
  await expect.poll(() => first!.evaluate((node) => node.isConnected)).toBe(false);
  await favorites.getByRole('button', { name: '← Volver', exact: true }).click();
  await expect(home).toBeVisible();
  await expect(draft).toHaveValue('');
  await expect(home.locator('[data-saved-note]')).toHaveText('Nota que debe sobrevivir');
  await expect(home.locator('[data-retention-pulses]')).toHaveText('0');
  await home.getByRole('button', { name: 'Enviar evento a las páginas retenidas', exact: true }).click();
  await expect(home.locator('[data-retention-pulses]')).toHaveText('1');
  expect(await first!.evaluate((node) => (node as HTMLElement & { retentionPulses: number }).retentionPulses)).toBe(1);
  const frame = exportedUrl ? page.mainFrame() : page.frames()[1];
  const counts = await frame.evaluate(() => [...document.querySelector('#app')!.children].filter((node) => node.tagName.endsWith('-PAGE')).length);
  expect(counts).toBe(2);
  await page.screenshot({ path: '/tmp/cells-retention-77-' + (exportedUrl ? 'exported' : 'playground') + '-desktop.png', fullPage: true });
  await home.getByRole('button', { name: 'Inglés', exact: true }).click();
  await expect(home.getByLabel('Local draft for this page')).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await home.getByLabel('Local draft for this page').fill('Mi próximo experimento');
  await expect(home.getByLabel('Local draft for this page')).toHaveValue('Mi próximo experimento');
  await home.getByRole('button', { name: 'Spanish', exact: true }).click();
  await expect(home.getByLabel('Borrador local de esta página')).toBeVisible();
  expect(await frame.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/cells-retention-77-' + (exportedUrl ? 'exported' : 'playground') + '.png', fullPage: true });
  await home.getByRole('button', { name: 'Buscar', exact: true }).click();
  const search = app.locator('academy-search-page');
  await expect(search).toBeVisible();
  await search.getByLabel('Buscar por nombre').fill('Clima');
  await expect(search.locator('academy-product-card')).toHaveCount(1);
  await expect(search.locator('academy-product-card')).toContainText('Proyecto Clima');
  await expect(search).not.toContainText('€');
  await search.getByLabel('Buscar por nombre').fill('No existe este proyecto');
  await expect(search.getByRole('status')).toContainText('No encontramos proyectos');
  await expect(search.locator('academy-product-card')).toHaveCount(0);
  expect(errors).toEqual([]);
  console.log(JSON.stringify({ lesson: 77, runtime: exportedUrl ? 'exported-open-cells' : 'playground', retainedDraft: true, evictedDraft: true, sessionNote: true, cleanup: true, retainedPages: counts, language: true, mobile: true }));
} finally {
  await browser.close();
}
